### ISSUE TITLE
target-async is deprecated

### ISSUE THREAD

**Issue by Torbjorn-Svensson** [eclipse-cdt/cdt#176]
When launching a debug session for a target, the following is printed in the GDB traces:

```
237,992 13-gdb-set target-async on
238,005 ~"Warning: 'set target-async', an alias for the command 'set mi-async', is deprecated.\n"
238,006 ~"Use 'set mi-async'.\n\n"
238,006 13^done
```

I suppose we should switch to the mi-async variant instead, but I don't see any easy way to accomplish that without code duplication and/or some kind of API break in the FinalLaunchSequence* classes.

Looking at the GDB sources, it appears it was introduced [329ea57934a9d4b250a0b417af1ec47bc2d0ceb6](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=329ea57934a9d4b250a0b417af1ec47bc2d0ceb6) and was first included in the GDB 7.8 release.

**Comment by Torbjorn-Svensson** [comment]
Do you think we can keep the `stepSetTargetAsync` but leave the implementation empty and then add a new `stepSetTargetAsync` or would that still break run-time behavior for extenders?

I agree that CDT11 is a good time this type of change, but I don't know if the time has run out for doing it...

@jonahgraham WDYT? Is this something that we should do?

I'm slammed with work for the rest of the week, so if one of you could look at this (if it's something we want to do for CDT11), I'd appreciate it.

**Comment by jonahgraham** [comment]
Please have a look at #177 that fixes this.

**Comment by jonahgraham** [comment]
> we don't use -gdb-set target-async on for GDB versions prior to

Actually we do, in non-stop mode in all versions of GDB:

https://github.com/eclipse-cdt/cdt/blob/1b19ba20c2df6da5c85d4019099e39cb2c4f1cb5/dsf-gdb/org.eclipse.cdt.dsf.gdb/src/org/eclipse/cdt/dsf/gdb/launching/FinalLaunchSequence.java#L405

**Comment by jld01** [comment]
> > we don't use -gdb-set target-async on for GDB versions prior to
> 
> Actually we do, in non-stop mode in all versions of GDB:

I missed that one. Could we override `stepSetNonStop` in `FinalLaunchSequence_7_12`? Or perhaps introduce a `protected boolean hasGDBSetMIAsync()` method in `FinalLaunchSequence` and override that in `FinalLaunchSequence_7_12` ?

**Comment by jonahgraham** [comment]
Its all handled with my patch. stepSetNonStop is already overridden in FinalLaunchSequence_7_12

**Comment by jonahgraham** [comment]
https://github.com/eclipse-cdt/cdt/blob/1b19ba20c2df6da5c85d4019099e39cb2c4f1cb5/dsf-gdb/org.eclipse.cdt.dsf.gdb/src/org/eclipse/cdt/dsf/gdb/launching/FinalLaunchSequence_7_12.java#L148
