### ISSUE TITLE
Can't install CDT due to JavaSE dependency

### ISSUE THREAD

**Issue by maccasoft** [eclipse-cdt/cdt#205]
CDT won't install on Eclipse 2022-12 due to a dependency to JavaSE not satisfied.

1. Downloading Eclipse SDK 4.26
2. Install CDT from Help -> Install New Software...

**Expected behavior**
Install CDT.

**Desktop:**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 22-04 LTS

**Additional context**

```
java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)

Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 18.0.0
  Software being installed: C/C++ Development Tools 11.0.0.202211300214 (org.eclipse.cdt.feature.group 11.0.0.202211300214)
  Cannot satisfy dependency:
    From: C/C++ Development Tools 11.0.0.202211300214 (org.eclipse.cdt.feature.group 11.0.0.202211300214)
    To: org.eclipse.equinox.p2.iu; org.eclipse.cdt.platform.feature.group [11.0.0.202211300214,11.0.0.202211300214]
  Cannot satisfy dependency:
    From: C/C++ Standard make Build Core 7.6.0.202211062329 (org.eclipse.cdt.make.core 7.6.0.202211062329)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=17))
  Cannot satisfy dependency:
    From: C/C++ Development Platform 11.0.0.202211300214 (org.eclipse.cdt.platform.feature.group 11.0.0.202211300214)
    To: org.eclipse.equinox.p2.iu; org.eclipse.cdt.make.core [7.6.0.202211062329,7.6.0.202211062329]
```

**Comment by maccasoft** [comment]
After digging the release notes, seems that CDT requires JavaSE 17, I was confused because the Eclipse SDK dosn't require it and tought that all projects agree on a common base... oh well.

Sorry, for the noise.

**Comment by jonahgraham** [comment]
No worries on the noise. I am glad you were able to resolve the issue on your own.

For others who come across this, the link to the release notes is: https://github.com/eclipse-cdt/cdt/blob/main/NewAndNoteworthy/CDT-11.0.md#java-17

>  I was confused because the Eclipse SDK dosn't require it and tought that all projects agree on a common base... oh well.

They do :-) The [current agreed on common base](https://wiki.eclipse.org/SimRel/Simultaneous_Release_Requirements#Execution_Environment_.28partially_tested.29) for Eclipse SimRel (starting with 2022-09) is Java 17, but there is no requirement that projects *have* to require Java 17. Soon after the next Java LTS version is out the common base will be upped to that version.
