### ISSUE TITLE
How do I use cdt Indexer outside of an eclipse project?

### ISSUE THREAD

**Issue by XrazYang** [eclipse-cdt/cdt#226]
Indexer is very powerful when parsing C++ projects using CDT. However, getting an indexer inevitably leads to a problem: "eclipse workspace is closed". Is there any way to use indexer outside of an eclipse project?

**Comment by zhizhixiongxuwei** [comment]
> Indexer is very powerful when parsing C++ projects using CDT. However, getting an indexer inevitably leads to a problem: "eclipse workspace is closed". Is there any way to use indexer outside of an eclipse project?

rewrite InternalFileContentProvider  and `IndexerInputAdapter`

**Comment by XrazYang** [comment]
Thank you very much for your reply, I tried to rewrite InternalFileContentProvider, but for IndexerInputAdapter, I don't know. Could you tell me more about the IndexerInputAdapter?

**Comment by XrazYang** [comment]
> 

Thank you very much for your reply, I tried to rewrite InternalFileContentProvider, but for IndexerInputAdapter, I don't know. Could you tell me more about the IndexerInputAdapter?

**Comment by XrazYang** [comment]
> > Indexer is very powerful when parsing C++ projects using CDT. However, getting an indexer inevitably leads to a problem: "eclipse workspace is closed". Is there any way to use indexer outside of an eclipse project?
> 
> rewrite InternalFileContentProvider and `IndexerInputAdapter`

Thank you very much for your reply, I tried to rewrite InternalFileContentProvider, but for IndexerInputAdapter, I don't know. Could you tell me more about the IndexerInputAdapter?

**Comment by zhizhixiongxuwei** [comment]
I think we can discuss this topic with QQ.

**Comment by XrazYang** [comment]
> I think we can discuss this topic with QQ.

Thank you, my qq, 1161051479. Or can I add you?

**Comment by zhizhixiongxuwei** [comment]
I can't find you.

**Comment by zhizhixiongxuwei** [comment]
QQ ->  694675325

**Comment by jonahgraham** [comment]
Thank you @zhizhixiongxuwei for stepping in and supporting @XrazYang on this. I hope this is resolved now. If not please reopen with further questions or create new issues or [discussions](https://github.com/eclipse-cdt/cdt/discussions).

**Comment by VenoVeno** [comment]
Can you add any sample snippet for this? @jonahgraham @zhizhixiongxuwei

**Comment by VenoVeno** [comment]
Can you add reference to the cpp-sensor project? @zhizhixiongxuwei

**Comment by zhizhixiongxuwei** [comment]
I can't find my demo project. The cpp-sensor project address is [cpp-sensor](https://github.com/juga999/cpp-sensor-core). 
According to the cpp-sensor you have to modify some files like PDOMWriter, PDOMName and so on. If you really need my code, I need to check my company PC and extract some core code.

**Comment by XrazYang** [comment]
@zhizhixiongxuwei hello，For the project cpp-senso, I have met many problems. Is it convenient for me to communicate through qq?
