### ISSUE TITLE
How can I use the specified objdump

### ISSUE THREAD

**Issue by laomaolaile** [eclipse-cdt/cdt#229]
I want to view the elf file in the project, but it is garbled，
Modify the configuration in .cproject, and change “org.eclipse.cdt.core.ELF” to “org.eclipse.cdt.core.GNU_ ELF“, eclipse can call objdump in the environment variable of the computer, but I want to specify my own objdump. How should I implement this?

![image](https://user-images.githubusercontent.com/19726057/210688923-694859e8-d134-4ccf-b59a-edfbd2ec9e14.png)
![image](https://user-images.githubusercontent.com/19726057/210688663-a2842962-3ec4-451c-89af-83dab5db8bc9.png)

The gcc I want to use is in my toolchain
![image](https://user-images.githubusercontent.com/19726057/210689677-8da4ba35-2182-40d2-8468-a5413f84ab1e.png)

**Comment by jld01** [comment]
Take a look at `org.eclipse.cdt.utils.DefaultGnuToolFactory.getObjdumpPath()` which implements the default behaviour. If you need to change this behaviour, you will need to override `getObjdumpPath()` in a subclass or experiment with providing the "objdump" extension data.

**Comment by laomaolaile** [comment]
> Take a look at `org.eclipse.cdt.utils.DefaultGnuToolFactory.getObjdumpPath()` which implements the default behaviour. If you need to change this behaviour, you will need to override `getObjdumpPath()` in a subclass or experiment with providing the "objdump" extension data.

Thank you for answering my question.
I guess that the "objdump" extension data can be passed in through "plugin.xml", but the correct method has not been found. Can you give me a demo for reference,Thank you very much.

**Comment by jld01** [comment]
We are working on improved support for `objdump` in issue #361.

**Comment by jld01** [comment]
[CDT 11.2.0 M2](https://download.eclipse.org/tools/cdt/builds/11.2/cdt-11.2.0-m2/) and later versions should support invoking the build of `objdump` provided by your own GNU toolchain on a generated ELF executable file as follows:

- Select the _GNU Elf Parser_ binary parser for each build configuration
- In the case of a cross-compilation toolchain, define a CDT _Build Variable_ named `gnu_tool_prefix` of type _String_ providing the tool name prefix including the trailing hyphen (eg `arm-none-eabi-`) for each build configuration

CDT will search for the `objdump` tool on the PATH configured for the relevant build configuration.

**Comment by jld01** [comment]
Issue is addressed via #361.
