### ISSUE TITLE
GCC Build Output Parser does not recognize -Isystem

### ISSUE THREAD

**Issue by stayprivate** [eclipse-cdt/cdt#236]
**Describe the bug**
The Build Output Parser does not seems to recognize the include path if the -I is suffixed with the  system attribute.

**To Reproduce**
I use a cmake project with custom Build Target (not the compilation database Parser). Because of cmake/ninja the build output is pretty much empty. I added a step in our build that will echo a dummy command line: 
echo "g++12  -Ifolder1 -Ifolder2 -Isystem folder3 ..."

Than after I build, I can see in the CDT Managed Build Settings Entries that folder1 folder2 are present but not folder3. If I replace -Isystem by -I, folder3 will show up 

**Expected behavior**
I looked at the documentation and could not find anything specific about -Isystem,  Maybe it is meant to be ignore ?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20

**Additional context**
Version: 2022-12 (4.26.0)
Build id: 20221201-1913

**Comment by jonahgraham** [comment]
Hi @stayprivate - thanks for the bug report. As you mention "CDT Managed Build Settings" and CMake it sounds like you are using [cmake4eclipse](https://github.com/15knots/cmake4eclipse)? If so, that bug report should be redirected to that project. If it can be reproduced with CDT on its own, I will need some more details on how to reproduce the problem.

**Comment by stayprivate** [comment]
Hello Jonah

Not using cmake4 eclipse. It's a "Makefile project for existing projet" but in our case we customize the build command to use cmake.  But cmake is not needed to reprocude this  

1 - Create a Makefile Project with existing code on a folder with a single .cpp, i use a.cpp. No need for makefile or cmake
2 - add a build target that will simply do an 
echo gcc -Isystem fail -I notfail  dummy.cpp
![image](https://user-images.githubusercontent.com/2780059/212743059-d6e173af-eb2f-425b-953f-40e7cc486651.png)
3 - Next set the CDT GCC Build Output Parser to use Projects:
![image](https://user-images.githubusercontent.com/2780059/212743207-63a43188-9790-4052-939d-ae8549b57b18.png)
4 - Build the test target

And you should see in the CDT GCC Build Output Parser Entries that the "fail" folder is not there but instead system is
![image](https://user-images.githubusercontent.com/2780059/212743422-3d55b7c5-73a8-4e70-abf1-3407a20527f6.png)

Thanks

- Mario

**Comment by jonahgraham** [comment]
Thanks for the extra context. I now know where to look in the code. GCC doesn't spell it like that, [GCC spells it `-isystem` ](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html) (lower case i) which CDT does recognize:

https://github.com/eclipse-cdt/cdt/blob/3feeedfa63ac4a01fca911a78376567c7d3c2bbb/build/org.eclipse.cdt.managedbuilder.core/src/org/eclipse/cdt/managedbuilder/language/settings/providers/GCCBuildCommandParser.java#L45-L47


Indeed if I run:

```
g++ -c a.cc -Isystem/tmp/a/q -v
```
I see this in the output of gcc:

```
ignoring nonexistent directory "system/tmp/a/q"
```

Doing:
```
g++ -c a.cc -isystem/tmp/a/q -v
```

gives:
```
#include <...> search starts here:
 /tmp/a/q
```

Please reopen this issue if I have misunderstood your problem.
