### ISSUE TITLE
Does not find current MSYS2 installation automatically

### ISSUE THREAD

**Issue by dallmair** [eclipse-cdt/cdt#237]
**Describe the bug**
On a Windows 11 machine, I installed MSYS2 64-bit. Unfortunately, CDT does not find this installation automatically, i.e. the MSYS_HOME environment variable in project properties under "C/C++ Build -> Environment" is empty.

**Diagnosis**
CDT searches the Windows registry for a package with DisplayName "MSYS2 64bit" or "MSYS2 32bit" [1]. However, in version 20221216 of MSYS2, such an entry does not exist. Nowadays it's just "MSYS2". See [2] for a full export of the respective registry key.

[1] https://github.com/eclipse-cdt/cdt/blob/main/core/org.eclipse.cdt.core/utils/org/eclipse/cdt/internal/core/MinGW.java#L231-L241
[2]

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{3598ecb0-d67f-432d-9780-b4c09da7a756}]
"DisplayName"="MSYS2"
"DisplayVersion"="20221216"
"DisplayIcon"="C:\\msys64\\uninstall.exe"
"Publisher"="The MSYS2 Developers"
"UrlInfoAbout"=""
"Comments"="MSYS2"
"InstallDate"="Tue Jan 10 11:51:53 2023"
"InstallLocation"="C:\\msys64"
"UninstallString"="\"C:\\msys64\\uninstall.exe\""
"ModifyPath"="\"C:\\msys64\\uninstall.exe\" --manage-packages"
"EstimatedSize"=dword:0004539c
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
```

**Comment by jld01** [comment]
Ref: https://github.com/msys2/msys2-installer/commit/19b98a20acc0da2805aa8f2f6be1041ada3ad67b#diff-bc88559aa7f913533c1dbeaae1c71f824d47c12c619c9e52d85710b871c1bb6a
