### ISSUE TITLE
TM Terminal: Bundle-RequiredExecutionEnvironment: JavaSE-17

### ISSUE THREAD

**Issue by jkoch70** [eclipse-cdt/cdt#249]
Hello,

We want to switch to newest Eclipse version 2022-12 for our product but we get an issue with TM Terminal.
The Bundle-RequiredExecutionEnvironment property in Manifest.mf files in TM Terminal bundles are set to JavaSE-17.
For example: org.eclipse.tm.terminal.connector.local_4.8.0.202211062329.jar.
In the older version of this bundle (org.eclipse.tm.terminal.connector.local_4.7.300.202204200013.jar) the Bundle-RequiredExecutionEnvironment property is set to JavaSE-11.

As Eclipse stated (https://www.eclipse.org/eclipse/development/readme_eclipse_4.26.php) that version 2022-12 runs with JavaSE-11, we would like to ask how to handle this issue.

Regards,

Jens

**Comment by akurtakov** [comment]
Link you point to is for Eclipse Platform not for every other plugin. Furthermore, it says that it requires *at least* Java 11 and many plugins in the simultaneous release require already Java 17 so if you are using a plugin that requires newer JVM just run eclipse with such new version and Eclipse Platform will handle that just as well as Java 11 (if not even better as many developers I know no longer even try Java 11).

**Comment by jkoch70** [comment]
We build our own Eclipse product and we have TM Terminal as a dependency provided via a P2 repository (https://download.eclipse.org/releases/2022-12/).
The problem is that our docker build images run Java11 and we are facing this error only for TM Terminal.
Same problem occurs when starting our product from inside Eclipse.
Once I remove TM Terminal from the start configuration, it works.

Switching to Java17 would mean, the entire team has to switch and all docker build images need to be updated.
We would like to avoid this step for now.

Do you plan to revert this change in your bundles?
When will an update be available?

**Comment by jonahgraham** [comment]
If you aren't ready to move to Java 17 then don't updare to CDT / TM Teminal 11 that is included in 2022-12.

There is nothing to be done here.

**Comment by akurtakov** [comment]
For the record - Eclipse Platform would move to Java 17 in the not so distant future.
