### ISSUE TITLE
testDCOM_BDFG (org.eclipse.cdt.ui.tests.text.doctools.DocCommentHighlightingTest) flaky

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#259]
The flaky test:

`testDCOM_BDFG (org.eclipse.cdt.ui.tests.text.doctools.DocCommentHighlightingTest)`

with this output;

```
expected:<[offset: 149, length: 17, offset: 184, length: 18, offset: 223, length: 16, offset: 241, length: 17, offset: 258, length: 16, offset: 345, length: 16]> but was:<[]>
junit.framework.AssertionFailedError: expected:<[offset: 149, length: 17, offset: 184, length: 18, offset: 223, length: 16, offset: 241, length: 17, offset: 258, length: 16, offset: 345, length: 16]> but was:<[]>
	at org.eclipse.cdt.ui.tests.text.doctools.DocCommentHighlightingTest.testDCOM_BDFG(DocCommentHighlightingTest.java:211)
```

**Comment by i-garrison** [comment]
This looks like a race in the test.
Adding a couple of sleeps and stepping through in debugger I seldom reproduce the issue with empty result from `findRangesColored()` and also managed to get different failure in nearby test `testDCOM_B` 
```
junit.framework.AssertionFailedError:
    expected:<[offset: 149, length: 17, offset: 345, length: 16]>
     but was:<[offset: 129, length: 18, offset: 328, length: 17]>
```

**Comment by jonahgraham** [comment]
Thanks @i-garrison for the investigation.

This is now failing basically all the time on GH Actions. I am now looking at this, either full fix, or apply ["flaky"](https://github.com/eclipse-cdt/cdt/blob/main/TESTING.md#marking-tests-as-slow-or-flaky) to it.

**Comment by jonahgraham** [comment]
The key thing is that makes `testDCOM_BDFG` different from the rest of the tests in `DocCommentHighlightingTest` is that it is run first. Therefore my guess is that some pre-existing state is not being cleared properly.
