### ISSUE TITLE
Builtin integer overflow functions not known

### ISSUE THREAD

**Issue by PhilippWendler** [eclipse-cdt/cdt#271]
GCC has a set of [builtin functions](https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html) for performing integer arithmetic with overflow checking, for example `__builtin_sadd_overflow` etc. These are not present in [CDT's list of builtin functions](https://github.com/eclipse-cdt/cdt/blob/a4ba7173e8b882fdeaa42255f764ec00301f4cb1/core/org.eclipse.cdt.core/parser/org/eclipse/cdt/internal/core/dom/parser/GCCBuiltinSymbolProvider.java), so code using them will be parsed with wrong types for these function calls.

It seems that adding them should be easy, however, there are some functions like `__builtin_add_overflow` which are declared like this:
```
bool __builtin_add_overflow(type1 a, type2 b, type3 *res)
```
`type1`, `type2`, and `type3` can be any integral type. How should this be represented inside CDT?

`__builtin_types_compatible_p`, which is also a builtin "function" with a signature that is not expressible in C , uses `""` as type for each parameter, which `createType(String)` seems to translate to a basic type with kind `eUnspecified` and no modifiers. Maybe this fits here as well? If yes, should the type of `res` be a void pointer or maybe something like `"*"`?

**Comment by jonahgraham** [comment]
@davmac314 did a few of the builtins last year, looking at [their contributions](https://github.com/eclipse-cdt/cdt/commits?author=davmac314) would be a good place to start on how to implement these.

**Comment by PhilippWendler** [comment]
Well, I already looked at the existing code and have an idea how to do it, but the questions that I mentioned regarding the types remain. If these are answered I can send a PR.

The contributions from davmac314 all seem to add concrete semantics for builtin functions for C++, this is not what I am attempting to do. I just want do add declarations.

**Comment by davmac314** [comment]
IIRC the type string is parsed as a C type (if it is not empty) by `createString(String)`. I think that for simply having the parser/checker accept calls to the function, the types should probably be `""` for the first two arguments (i.e. don't check the argument types), and `"void*"` would work reasonably well for the third (make sure that a pointer is passed, though it will not check if the pointer is the correct type).
