### ISSUE TITLE
Checker fails to capture Across Class Issue

### ISSUE THREAD

**Issue by VenoVeno** [eclipse-cdt/cdt#280]
Hi,

The [AssignmentToItselfChecker.java](https://github.com/eclipse-cdt/cdt/blob/main/codan/org.eclipse.cdt.codan.checkers/src/org/eclipse/cdt/codan/internal/checkers/AssignmentToItselfChecker.java) captures Self assignments within the same translation unit. But if the value propagates through header and the same assignment is done, it won't capture, which is quite as expected. I'm running this as a standalone Parser [link](https://github.com/VenoVeno/CDT-Failed-Demo/blob/main/SampleParser.java). 

#### A.c
```
#include <stdio.h>

#include "A.h"

int main() {
    int number1 = 100;
    number1 = callMe(number1);

    int number2 = 100;
    number2 = number2;
}
```

#### A.h:
```
int callMe(int number) {
    return number;
}
```

Github Source : [repo](https://github.com/VenoVeno/CDT-Failed-Demo/tree/main)

Is there any working solution to achieve this using Taint Analysis or lookup in other translation unit? Any working solution without IDE (Standalone) is fine. May be i'm missing something that's already available. Correct me if i'm wrong anywhere.

Thanks in advance.

**Comment by VenoVeno** [comment]
@jonahgraham

**Comment by jonahgraham** [comment]
> @jonahgraham

Sorry, I don't know.

**Comment by jonahgraham** [comment]
What I do know is that codan is an "extra" thing that runs, it is not part of a normal AST creation. Not sure how to hook codan into a standalone, or if it is even possible.

**Comment by VenoVeno** [comment]
@jonahgraham 

If it is not possible, then how does Eclipse lookup method implementation in another class or header included in the original source. (Go to Implementation).

Correct me if i'm wrong, eclipse will index all the files in the workspace. When the "Go to Implementation" is clicked, does it lookup using `Index`?

**Comment by jonahgraham** [comment]
Yes, it does indeed use the index to look it up

**Comment by VenoVeno** [comment]
The entire thing is managed by eclipse IDE? Is it possible to do this thing standalone without the Eclipse IDE?

**Comment by jonahgraham** [comment]
Short answer is no, at least not as far as I know. You can look at Codan code base and see what it would take to refactor it.

**Comment by jonahgraham** [comment]
I don't think there is anything to do in this issue. I am closing this, but if there is some additional work you can create specific issues.
