### ISSUE TITLE
Null check missing for input argument (source) when updating Disassembly view

### ISSUE THREAD

**Issue by LizzMre** [eclipse-cdt/cdt#287]
**Repo:** https://github.com/eclipse-cdt/cdt/tree/main/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly

**Bug Description**

***Scenario***
Let’s consider that we have a Client-Server architecture where the server is sending to the client information on which lines to append to the Disassembly view from a specific file. 
There might be a possibility for the server to send some incorrect data, for example: sending additional lines that cannot be found in the associated file. 
In this case, the GUI will display a NullPointerException when trying to fetch the lines that don’t exist.
Even though the server might send incorrect data, it would be nice to provide the user a message with a suggestive description of the issue and prevent the GUI from crashing. 

***Code flow***
1. Information was received and it will reach the following line:
[SourceColorerJob.runInUIThread() -> line 63](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/SourceColorerJob.java#L63)
<img width="469" alt="image" src="https://user-images.githubusercontent.com/103601453/219044844-2a72cd4b-86da-4ca1-be73-78668cacc41d.png">

2.  Next, the following method will be called:
[DisassemblyPart.updateInvalidSource() -> line 1706](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/DisassemblyPart.java#L1706)
![image](https://user-images.githubusercontent.com/103601453/219044498-6106899f-199e-4d97-8103-2e9bbc3dbf7f.png)

3. From here, for each line (that must be fetched from the file) it will reach the following method: [DisassemblyPart.insertSource() -> line 2756](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/DisassemblyPart.java#L2756) that has multiple blocks of code similar to the sample below:

***Sample from this method***
![image](https://user-images.githubusercontent.com/103601453/219049200-f1d9d7a3-407f-4d10-bb45-bbd9a16f6413.png)
    
4. In this method, there are some calls on [SourceFileInfo.getLines()](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/SourceFileInfo.java#L136) method, that will return null if it fails to get the lines from the file.
<img width="491" alt="image" src="https://user-images.githubusercontent.com/103601453/219050654-b5a024a2-edda-4899-9f94-f4c4c297eec8.png">

5. After the lines (source) were extracted from the file, it goes back to step 3 and it will call [DisassemblyDocument.insertSource()](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L1229) where the source is processed, therefore it should not be null.
<img width="493" alt="image" src="https://user-images.githubusercontent.com/103601453/219052552-1e5708e1-79d8-47e4-b758-7936d6c6e3fe.png">

***Bug***
If a line does not exist within the file, [SourceFileInfo.getLines()](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/SourceFileInfo.java#L136) will catch the BadLocationException and return null (See step 4).
The source will be null and sent to [DisassemblyDocument.insertSource()](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L1229) (See step 3).
When reaching step 5, there will be a NullPointerException for [source.isEmpty()](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L1233) and the GUI will display the following problem:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/103601453/219054758-0cde6a06-1df1-4dfd-a3e6-97eb074296cd.png">

**To Reproduce**

The issue has occurred in an isolating case described in the ***Scenario***, but in order to forcingly reproduce the issue, there might be two ways:

1.  Make the source null. Above line 1232 from [DisassemblyDocument.insertSource()](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L1232), we can add ***source = null;***.

2.  Force fetching lines that don't exist in the file. Above line 138 from [SourceFileInfo.getLines()](https://github.com/eclipse-cdt/cdt/blob/590906a0058bb093f0d9b38c2ac49bb73c5227fe/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/SourceFileInfo.java#L138), we can add:
***int forceOffset = 10;
first = fSource.getNumberOfLines() + forceOffset;***

**Expected behavior & Potential fix**

1. At step 3 from ***Code flow***, if [fi.getLines()](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/SourceFileInfo.java#L136) returns null, then [fDocument.insertSource()](https://github.com/eclipse-cdt/cdt/blob/590906a0058bb093f0d9b38c2ac49bb73c5227fe/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L1229) should not be called, but instead the [fDocument.removeSourcePosition(pos)](https://github.com/eclipse-cdt/cdt/blob/590906a0058bb093f0d9b38c2ac49bb73c5227fe/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L760) should be called because the source position (pos) is not valid. 
2. At step 5 from ***Code flow***, a null check before line 1232 in [DisassemblyDocument.insertSource()](https://github.com/eclipse-cdt/cdt/blob/590906a0058bb093f0d9b38c2ac49bb73c5227fe/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L1232) could prevent a NullPointException from happening.
3. At step 4 from ***Code flow***, if [BadLocationException ](https://github.com/eclipse-cdt/cdt/blob/920f7d85a56bf60e9e5befeea42779bf9b4021d2/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/SourceFileInfo.java#L149) is caught, it might be useful to have a Message Dialog box notification to inform the user on the issue that occurred.
*According to the string’s externalization guidelines, this might not be approved, but it might be helpful for a user to debug the issue.

**Additional information**

I would be interested in creating a Pull Request to fix this issue, but I would like a confirmation on the issue described above first. Also, please address me any questions if something is not clear!

Thank you!

**Comment by jonahgraham** [comment]
_Hi @LizzMre - sorry for the delay in responding. I thought I had replied, but I must have lost my draft, so here we go from scratch:_

> I would be interested in creating a Pull Request to fix this issue, but I would like a confirmation on the issue described above first. Also, please address me any questions if something is not clear!

I am delighted to received a PR on this issue. Your analysis of the problem looks sound.

> **Expected behavior & Potential fix**
> 
> 1. At step 3 from Code flow, if [fi.getLines()](https://github.com/eclipse-cdt/cdt/blob/58ab28dfd120c5c6fd320c51949d5cf0d245ff5b/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/SourceFileInfo.java#L136) returns null, then [fDocument.insertSource()](https://github.com/eclipse-cdt/cdt/blob/590906a0058bb093f0d9b38c2ac49bb73c5227fe/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L1229) should not be called, but instead the [fDocument.removeSourcePosition(pos)](https://github.com/eclipse-cdt/cdt/blob/590906a0058bb093f0d9b38c2ac49bb73c5227fe/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L760) should be called because the source position (pos) is not valid.

Yes, that is a good solution.

> 2. At step 5 from Code flow, a null check before line 1232 in [DisassemblyDocument.insertSource()](https://github.com/eclipse-cdt/cdt/blob/590906a0058bb093f0d9b38c2ac49bb73c5227fe/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/DisassemblyDocument.java#L1232) could prevent a NullPointException from happening.

That also works, and this option is the minimal change to get rid of the NPE AFAICT. 

> 3. At step 4 from Code flow, if [BadLocationException ](https://github.com/eclipse-cdt/cdt/blob/920f7d85a56bf60e9e5befeea42779bf9b4021d2/dsf/org.eclipse.cdt.dsf.ui/src/org/eclipse/cdt/dsf/debug/internal/ui/disassembly/model/SourceFileInfo.java#L149)is caught, it might be useful to have a Message Dialog box notification to inform the user on the issue that occurred.

I don't think there should be a message dialog here. This is because AFAIU this would be a programming error that the user cannot do anything about. Instead I would log the error to the error log. If there is some corrective action the user can take, then displaying the dialog is helpful. It is also suitable to use the dialog if the failure is such that there is no other way to indicate to the user that the displayed values are now incorrect, however I don't think this applies based on your proposal in 1.

**Comment by LizzMre** [comment]
Hi @jonahgraham 

Thank you for your response! I will take into consideration your suggestions and I will create a PR on this issue.
