### ISSUE TITLE
Eclipse CDT Parser failed to parse MSVC developed C++ Code.

### ISSUE THREAD

**Issue by VenoVeno** [eclipse-cdt/cdt#292]
Hi,
Eclipse CDT Parser failed to parse MSVC developed C++ Code. Am i missing any macro or includes?
Used [this](https://github.com/VenoVeno/CDT-Failed-Demo/blob/main/SampleParser.java) parsing logic to parse CPP source. If MSVC is not supported, if there any way to skip the keywords and parse the Statement? 

Kindly, suggest a working solution.

### Sample Snippet:

```
# Filename : Failure.cpp
EXTERN_C IMAGE_DOS_HEADER __ImageBase;

int main()
{
    hr = SafeArrayAccessData((SAFEARRAY *)(var.pparray), (void HUGEP *FAR *)&pVar);
    NEW(rowList, ROWHOLDER*, count);
    logName = logName + std::string(" " DETOURS_STRINGIFY(DETOURS_BITS));
}

HRESULT WindowsFirewallInitialize(SyMNative *symNative, OUT INetFwProfile **fwProfile)
{
}

DWORD retrievePackageInfo(Windows::ApplicationModel::Package ^ package, JSON_DO &metroPackages)
{
}

[STAThread]
int wmain(Platform::Array<String^>^ args)
{
}
```

Translation Unit's ASTProblem Node:
![Screenshot from 2023-02-16 19-57-41](https://user-images.githubusercontent.com/40896558/219393265-2369d5bf-cd50-4c4c-82d7-bf9f4a0a19cb.png)

Thanks.

**Comment by VenoVeno** [comment]
Any update on this issue?

**Comment by VenoVeno** [comment]
@jonahgraham Any update on this issue?

**Comment by jonahgraham** [comment]
> @jonahgraham Any update on this issue?

No.

**Comment by VenoVeno** [comment]
Can you add any person to solve the issue?

**Comment by jonahgraham** [comment]
You can try emailing [cdt-dev](https://github.com/eclipse-cdt/cdt/blob/main/CONTRIBUTING.md#contact). It would be helpful if you can include a reproducible problem, or at least point out where in the code example what the problem is. For example, is the problem with `EXTERN_C` macro as the ASTProblem indicates? Does the problem exist only with:

```c
EXTERN_C IMAGE_DOS_HEADER __ImageBase;
```

Do you have includes setup to provide the macro expansions of `EXTERN_C` and `IMAGE_DOS_HEADER`?


It would also be helpful to include actual text in your description and not just screenshots of text. The screenshots can help provide context, but the text itself should be included too.

**Comment by MarkZ3** [comment]
It looks like managed C/C++, it's doubtful CDT will ever support this using its internal parser. There is some MSVC support if you use non-managed code. For example, the CDT parser will detect if _MSC_VER is defined and turn on parsing of some built-in functions. There is also some hard-coded built-ins defined through macros if you create a Managed C/C++ project with MSVC toolchain (like __cdecl, etc). But I'm not aware of any support for pointers to managed memory for example (caret character) so those probably cause syntax errors and many resulting problems.

**Comment by VenoVeno** [comment]
This is not a eclipse developed project. It's developed in Microsoft Visual Studio platform written based on windows based.

**Comment by MarkZ3** [comment]
Sorry, I shouldn't have mentioned the Managed build projects, it doesn't help you in your case anyway. The gist of it is that the CDT parser is not able to parse the Microsoft-specific syntax and I doubt it ever will. You could define things like EXTERN_C through macros but it will still fail to parse caret pointers.

**Comment by VenoVeno** [comment]
Well thanks for your reply.
