### ISSUE TITLE
can not prevent the debugger from stopping on the first line

### ISSUE THREAD

**Issue by wangjinwan** [eclipse-cdt/cdt#293]
**Describe the bug**
using CDT to develop the C++ program,

after I choosen the project and enable the GDB,  it always stop at first line
even after i  disabled the "stop at the startup at main" in the GDB setting

**To Reproduce**
1. create a C++ project 
2. compile the project
3. attach the debug

**Expected behavior**
Dont stop at the first line.

**Screenshots**
![企业微信截图_16766169891072](https://user-images.githubusercontent.com/125635203/219571981-f83acbde-f362-48c2-a000-f0b97
![企业微信截图_16766169352606](https://user-images.githubusercontent.com/125635203/219571991-6a2f8d2c-4ef2-4867-85aa-184ba7d1bcdb.png)
431a1f8.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser dont needed
 - Version dont needed

**Additional context**

**Comment by jonahgraham** [comment]
When _attaching_  to a running process gdb always suspends that process. Then the user can press continue if they didn't want to suspend. 

The *stop at startup* option really just inserts a temporary breakpoint at the given symbol.

Therefore, I think that CDT is working as intended.

If the above doesn't answer your query or if I didn't understand what you meant, please provide the additional details requested below and reopen the issue.

> Version dont needed

Please provide some details about which version of the tools you are using? e.g. which version of gdb, cygwin, msys2, mingw or other?

Can you also please provide the [gdb traces](https://github.com/eclipse-cdt/cdt/blob/main/FAQ/README.md#ive-been-asked-for-gdb-traces-where-can-i-find-them)?
