### ISSUE TITLE
mingw detector causes NPE

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#330]
### Discussed in https://github.com/eclipse-cdt/cdt/discussions/329

mingw detector code generates an NPE. This appears to be a regression introduced by #243

`displayName` in this bit of code can be `null` leading to an NPE because `MSYS2_64BIT_NAMES` doesn't allow `null` values so you can't even to `contains(null)` on it.

https://github.com/eclipse-cdt/cdt/blob/2b297c4355a07ec26b68c88cc1d8d0bbcab87186/core/org.eclipse.cdt.core/utils/org/eclipse/cdt/internal/core/MinGW.java#L97-L99

The same issue is here:

https://github.com/eclipse-cdt/cdt/blob/a949830dd36a84297cac39452f725dad9ef9875c/build/org.eclipse.cdt.build.gcc.core/src/org/eclipse/cdt/build/gcc/core/internal/Msys2ToolChainProvider.java#L50

I think the fix is simply adding a null check (or using a set that allows `null`).

cc @jld01

**Comment by jonahgraham** [comment]
There is a workaround - adding a `DisplayName` value to the keys under `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall` in the registry.

**Comment by jonahgraham** [comment]
Re-opening until the fix is applied to 11.1 branch.

**Comment by jonahgraham** [comment]
[CDT 11.1.1](https://github.com/eclipse-cdt/cdt/releases/tag/CDT_11_1_1) has now been deployed that contains this fix.

**Comment by jld01** [comment]
Thanks for sorting this out @jonahgraham. Out of interest, did you see this issue locally? Just wondering why I didn't see it myself.

**Comment by jonahgraham** [comment]
No worries. I did see it locally, the entry missing `DisplayName` was a citrix connection. Not sure how widely seen it will be in practice, but as the `Uninstall` registry entry seems like one of those that can fill with cruft over the years it seems likely. 

BTW I didn't realize that `Set.of().contains(null)` threw an NPE as `Collections.emptySet().contains(null)` returns `false` (as does a "normal" `HashSet`).
