### ISSUE TITLE
Support IEditorAssociationOverride

### ISSUE THREAD

**Issue by ghentschke** [eclipse-cdt/cdt#341]
We are currently working on a new [LSP based C/C++ Editor](https://github.com/Bachmann-electronic-GmbH/eclipse-cdt-lsp).
Currently I'am working on this [issue](https://github.com/Bachmann-electronic-GmbH/eclipse-cdt-lsp/issues/37)

The file association for C/C++ source or header file to an editor should be dependent on the project settings. Therefor the user can select to prefer the new LSP based editor for his project.

The current implementation to override the default association of an editor to a file is based on this extension point: `org.eclipse.ui.ide.editorAssociationOverride`

The problem is that the cdt method `org.eclipse.cdt.internal.ui.util.EditorUtility.getEditorID(IEditorInput, Object)`  does not care about the overriden default editor by the implementation of `org.eclipse.ui.ide.editorAssociationOverride`.

The fix are 5 lines of code in `org.eclipse.cdt.internal.ui.util.EditorUtility.getEditorID(IEditorInput, Object)`:
![image](https://user-images.githubusercontent.com/123444711/227997331-28b040ec-b5ff-4053-b352-1bbcf031a3ae.png)

The charm of this solution is, that the default C/C++ editor can be overriden by the  `org.eclipse.ui.ide.editorAssociationOverride` extension point.

**Comment by jonahgraham** [comment]
This looks good to me (but may need a null check on return of getEditorDescriptor?). Can you provide a PR so we can proceed?

**Comment by ghentschke** [comment]
I'll provide a pull request. Null check should not be necessary. The method `getEditorDescrioptor` will throw a `PartInitException` if no valid editor can be found.

**Comment by jonahgraham** [comment]
Fixed by #345
