### ISSUE TITLE
LSP / clangd support for C/C++ in CDT

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#354]
An important part of the future of Eclipse CDT is improving language support. The long term future of this is expected to be done by integrating clangd via LSP. 

@ghentschke [announced](https://www.eclipse.org/lists/cdt-dev/msg35445.html) in February that she and others (Bachmann electronic, Renesas and Espressif Systems) are working on that in https://github.com/Bachmann-electronic-GmbH/eclipse-cdt-lsp repo.

This was also extensively [discussed](https://www.eclipse.org/lists/cdt-dev/msg35452.html) at the last monthly CDT call.

This issue is to track progress on migrating the work started in  https://github.com/Bachmann-electronic-GmbH/eclipse-cdt-lsp to be hosted by Eclipse CDT itself. Steps to migrate the work:

- [x] IP Approval as the code change is > 1000 lines.
- [x] Request EF Webmaster move the repo to the eclipse-cdt GitHub organization
- [x] Submit committer elections
- [x] Update links from https://github.com/Bachmann-electronic-GmbH/eclipse-cdt-lsp -> https://github.com/eclipse-cdt/cdt-lsp/
- [x] Create initial pre-releases of the code

**Comment by jonahgraham** [comment]
IP approval requested in https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7767

**Comment by jonahgraham** [comment]
> IP approval requested in https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7767

Done.

The request to transfer has been started here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3048

@ghentschke can you please comment on that issue so that Eclipse Webmaster has your confirmation and contact details please?

**Comment by jonahgraham** [comment]
> The request to transfer has been started here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3048

Transfer complete  - https://github.com/eclipse-cdt/cdt-lsp

Election has now started for @ghentschke   https://projects.eclipse.org/projects/tools.cdt/elections/election-gesa-hentschke-committer-eclipse-cdt%E2%84%A2-cc-development-tooling

**Comment by jonahgraham** [comment]
On the CDT call today we agreed to aim for a May 21 pre-release of the LSP work in conjunction with 2023-06 M3.

**Comment by fgelm01** [comment]
What impact will switching to clangd have on those aspects where Eclipse currently provides a better experience? Of particular interest to me is code assistance inside function template definitions. See my [comment](https://github.com/clangd/clangd/issues/443#issuecomment-1575757805) for details.

Briefly:
```cpp
void test(vector<pair<A, B>>& vec) {
  vec.front().  // cursor here
}
```
Eclipse helpfully suggests `.first` and `.second`, but a clangd based editor either provides no suggestions, or only unhelpful ones.

I have been quietly using Eclipse for years to write some very template-heavy C++, and a regression to code assistance in such situations would make me very sad.

**Comment by jonahgraham** [comment]
_Hi @fgelm01 - thanks for the question, years of use, and the referenced bug report!_

There is no plan yet to get rid of the current parser in CDT. There is substantial investment in it by users and extenders of CDT. However, as you showed in bug report #406, there are many things in C++ that CDT does not support at the moment. That combined with insufficient investment in CDT's parser to keep up with C++ (and C) standards leaves CDT unable to handle more and more cases.

We have thankfully had a number of improvements to C++ support in 2023-03 (11.1) and upcoming 2023-06 (11.2), but I don't think that comes close enough to supporting all of C++ and therefore the long term strategy is to leverage clangd via LSP to support C++ into the future.

For now using LSP is a [preference](https://github.com/eclipse-cdt/cdt-lsp#activating-lsp-based-cc-editor) (either per workspace or per project) and I expect that to remain the case for many years to come. 

Finally, as you have a reproducible test case where clangd is inferior to CDT, I would encourage you to submit that to [clangd's bug tracker](https://github.com/clangd/clangd/issues) so that by the time CDT provides this integration as standard out of the box (e.g. changing the default value of the aforementioned preference) the experience for CDT users won't be worse.

**Comment by jonahgraham** [comment]
>  Create initial pre-releases of the code

This was announced recently on [cdt-dev](https://www.eclipse.org/lists/cdt-dev/msg35471.html).

This will also be presented at the [upcoming quarterly webinar](https://wiki.eclipse.org/Eclipse_IDE_Webinar_2023-06) on June 15th.
