### ISSUE TITLE
Consider filtering nested projects from org.eclipse.cdt.root

### ISSUE THREAD

**Issue by merks** [eclipse-cdt/cdt#37]
The org.eclipse.cdt.root contains the entire working tree of the repository.  That's of course convenient for making root files and intermediate pom.xml files available in the workspace. 

But it also leads to 'duplicate' resources in the workspace.  E.g., this search finds two matches but there is really only one underlying file in the file system:

![image](https://user-images.githubusercontent.com/208716/184300496-adba2428-5f22-4daa-b308-4ee175e431a6.png)

Given the highly regular naming conventions of the project folders, a simple exclusion filter can filter out the contents under nested projects so that you can still see the project names but not the duplicate child content.  Search works better then too:

![image](https://user-images.githubusercontent.com/208716/184302444-b5c7c02d-c0f5-49bd-bdd4-c72ec727a171.png)

The filter is added/modified like this from the project's properties:

![image](https://user-images.githubusercontent.com/208716/184302799-f100cc58-dc5e-48f5-8355-377f384f89b1.png)

Are you interesting this.  I can provide it via a PR if so.

**Comment by ruspl-afed** [comment]
Dear @merks 
Yes, please do so. Most probably this root project was introduced by me to simplify massive repackaging and releng tasks.
Also, what could be very useful is Working Set per "component subfolder" like: build, cmake, codan, etc.

**Comment by merks** [comment]
Yes, updated working sets is what I'm working on at the moment.  😄

**Comment by jonahgraham** [comment]
AFAICT this is now complete. Thanks Ed for the improvement and Alexander for review and merge.
