### ISSUE TITLE
Launch configuration runs wrong build configuration of Core Build project.

### ISSUE THREAD

**Issue by ewaterlander** [eclipse-cdt/cdt#378]
The Core Build Makefile/CMake projects create too simple launch configurations. To run the binary of my Core Build Makefile project I need to create a "C/C++ Application" launch configuration to be able to set options for the launching. For debug I create a "C/C++ Remote Application" launch configuration.

The problem is that a normal "C/C++ Application" launch configuration can't control which build configuration of a Core Build project to run. Therefore the incremental build can build with wrong options.
Once the project was once compiled for Debug, using the Core Build launch configuration, the  "C/C++ Application" will always compile for debug, no matter what the launch type setting in the launch bar is.

**To Reproduce**
1. Create a new (Experimental) Makefile project with a hello world program.
2. Build it, run it. With the automatically created launch configuration.
3. Set launch type to Debug in the LaunchBar
4. Build for Debug, and run a debug session.
5. Set launch type back to Run in the LaunchBar.
6. Clean the project.
7. Build and run the project in Run mode.
8. Create a "C/C++ Application" launch configuration, select the Run binary, without debug.
9. Select the new launch configuration.
10. Run the new launch configuration.

You can see the project is build with flag -g. The expected flag would be -O2.

![image](https://user-images.githubusercontent.com/102143930/233969694-9dfea88c-1a57-41ed-ba67-40114fd62689.png)

The normal (not Core Build) launch configurations have no option to select a specific build configuration of a Core Build project that could be used to force a specific build configuration (which can be done for managed build projects).

![image](https://user-images.githubusercontent.com/102143930/233970690-e9221e3f-25c1-4c3b-944e-c15a8f80cdb1.png)

**Expected behavior**
The proper build configuration should be built based on the launch type set in the launch bar.

Workaround: Select the core build launch config, build for Run, select the "C/C++ Application" launch config, and launch.

OS: Linux.

**Comment by ewaterlander** [comment]
The problem is in CoreBuildLaunchBarTracker.setActiveBuildConfig().
In the sub method run() it picks a build configuration based on a tool chain match. It ignores the launch type setting and favors the non default build configuration (Debug) over the default (Run).
So setting the LaunchType to Run in the LaunchBar sets the active build configuration to Debug.
Core Build launching doesn't use the active build configuration for starting the incremental build, but normal launch configurations do.

**Comment by ewaterlander** [comment]
I'm creating a PR for this issue.

**Comment by jonahgraham** [comment]
Thanks @ewaterlander for the fix, and thanks @betamaxbandit for the review.
