### ISSUE TITLE
Memory view table cell editing is broken 

### ISSUE THREAD

**Issue by kudbudeen1** [eclipse-cdt/cdt#381]
Table Cell editing in memory view is broken. When trying to update the value of an address in the memory view cell, It does not show the editing field or the new value entered. The new value is shown only after the "Enter" key or focus out of the cell. 

**To Reproduce**
1. Create Helloworld C++ project and launch debug session using GDB.
2. Add a new memory monitor with valid address.
3. Try to edit the memory view cell to enter a new value
4. Note that the editing is not working and the new value is shown only after the "Enter" key

**Expected behavior**
Memory view should show the table cell editing behavior and the new value as the user types in.

 - OS: RHEL
 - OS Version - 7.8, 8.1 & 8.4
 - Eclipse versions - Checked with 4.16, 4.25 and 4.27(latest)
 - GTK - 3.22.30

**Comment by jonahgraham** [comment]
I can confirm this, here is a little animated gif. I start and the value is 5678, I type 4321 and press enter and the UI does not show me anything while typing.

![Peek 2023-04-25 14-42](https://user-images.githubusercontent.com/679236/234372127-0f957a6c-04ca-4fac-ad50-cdc138a8ebf1.gif)

I suspect this is a bug outside of CDT itself though as most (all?) of the UI here comes from the [Eclipse Platform Debug components](https://github.com/eclipse-platform/eclipse.platform.debug). Filing the bug there would be useful, but really we need to be able to reproduce it without CDT to get anyone to pay attention probably.

**Comment by jonahgraham** [comment]
Issues moved to https://github.com/eclipse-platform/eclipse.platform.debug/issues/132

**Comment by jonahgraham** [comment]
Thanks to @gsrinivas37 for fixing this issue in the Eclipse Platform. @kudbudeen1 the fix will be available in 2022-06 release. Thank you for taking the time to submit the issue.

If you are able to test the change, please download 2022-06 M3 (Milestone 3) when it is published on May 19.
