### ISSUE TITLE
Improve CDT's setup

### ISSUE THREAD

**Issue by merks** [eclipse-cdt/cdt#39]
I'm doing several things that once.  I hope that's okay.

I added a configuration in the same folder as the setup. It's reference via an annotation in the project (so that the setup archiver can discover it and include it in the setups.zip):

![image](https://user-images.githubusercontent.com/208716/184330849-fb41deac-823a-4500-9614-b3e6c5ad56a1.png)

The configuration installs the latest available committers product and the workspace includes the main branch of the CDT project setup.

I've simplified the targlet definition:

![image](https://user-images.githubusercontent.com/208716/184331306-8cd2141d-5c6c-47ee-8aee-21790c55bcc9.png)

I've tried as must has possible to use moving target (latest) repos where available so that developers notice problems introduced upstream early when they are first introduced.

This lead to two compile problems in two tests projects that I fixed with package imports and you'll see in the PR.

I've modified the working sets so that there is one per subfolder:

![image](https://user-images.githubusercontent.com/208716/184331782-40902e44-929e-4426-a844-b3bbc5e58143.png)

The first working set is any project not part of the subsequent working sets, i.e., currently just the org.eclipse.cdt.root project.

So the workspace now is organized like this:

![image](https://user-images.githubusercontent.com/208716/184332133-3f273b30-899e-449d-ab73-f9dbe6b0a967.png)

**Comment by merks** [comment]
@jonahgraham @ruspl-afed 

The API baseline in the setup still looks over complicated to me.   But looking at /org.eclipse.cdt.target/cdt-baseline.target I think that too is overly complicated and that it is not up-to-date.   It uses this p2 site:

![image](https://user-images.githubusercontent.com/208716/184526503-10c8a285-3e0b-4b0a-a6af-6783cb06121d.png)

But the latest release is 

![image](https://user-images.githubusercontent.com/208716/184526519-8c6aa3b5-f3b6-434d-96dc-d932ece99bf3.png)

So why not use this URL?

https://download.eclipse.org/tools/cdt/releases/latest/

I've not used API baseline tools in any of my projects so forgive if this is a stupid question, but what is the purpose of the other locations?  Probably because planner mode is used but in the end, only the plugins and features present in the git repository need to be in the API base for comparison, right?  So one could just have the single location of the most recent release and use slicer mode I think.  Or am I misguided?

I believe the API baseline target could be reduced to this:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="Generated from CDT" sequenceNumber="36">
  <locations>
    <location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="false" type="InstallableUnit">
      <unit id="org.eclipse.cdt.autotools.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.build.crossgcc.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.cmake.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.core.autotools.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.debug.dap.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.debug.dap.gdbjtag.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.debug.gdbjtag.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.debug.standalone.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.debug.ui.memory.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.docker.launcher.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.examples.dsf.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.gnu.multicorevisualizer.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.jsoncdb.arm" version="0.0.0"/>
      <unit id="org.eclipse.cdt.jsoncdb.hpenonstop" version="0.0.0"/>
      <unit id="org.eclipse.cdt.jsoncdb.intel" version="0.0.0"/>
      <unit id="org.eclipse.cdt.jsoncdb.microsoft" version="0.0.0"/>
      <unit id="org.eclipse.cdt.jsoncdb.nvidia" version="0.0.0"/>
      <unit id="org.eclipse.cdt.launch.remote.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.launch.serial.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.llvm.dsf.lldb.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.lsp.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.managedbuilder.llvm.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.meson.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.msw.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.qt.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.sdk.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.testsrunner.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.unittest.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.cdt.util" version="0.0.0"/>
      <unit id="org.eclipse.cdt.visualizer.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.launchbar.remote.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.remote.console.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.remote.proxy.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.remote.serial.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.remote.telnet.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.tm.terminal.connector.cdtserial.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.tm.terminal.connector.remote.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.tm.terminal.feature.feature.group" version="0.0.0"/>
      <repository location="https://download.eclipse.org/tools/cdt/releases/latest"/>
    </location>
  </locations>
</target>
```
This would always follow the latest release properly and the set of IUs would need to be updated only if you added a plugin or feature but do not also include it in any existing feature but rather add it directly to the category.xml.  In other words, the above list is minimized to eliminate IUs that are included but other IUs in the list, so the above are the root IUs of the inclusion tree.

Based on this, I can minimize the targlet for the API baseline to match...

**Comment by jonahgraham** [comment]
I haven’t tried planner vs slicer in the past to see if that solves the dependencies. But CDT has very many dependencies, so it doesn’t surprise me we have these projects listed

As for 10.6 vs 10.7 as baseline. The main branch has not actually been setup for post 10.7 dev yet. I need to find time to run through that checklist. IE what is needed is https://github.com/eclipse-cdt/cdt-infra/issues/59 done for next version.

**Comment by jonahgraham** [comment]
Thanks Ed for all the improvements. If there is more ideas please let us know.
