### ISSUE TITLE
TM Terminal: backspace deletes whole word

### ISSUE THREAD

**Issue by mlocati** [eclipse-cdt/cdt#392]
I've installed Eclipse 2023-03 (Platform 4.27.0.v20230302-0300) and TM Terminal 11.1.0.202212091724.

In the Terminal view, when I hit the backspace character, the console deletes the whole word on the left instead of a single character.

This happens consistently on two Windows 11 PCs.

I've also tried installing Eclipse (Eclipse IDE for PHP Developers) in a Windows Sandbox: same error.

Here's a sample session:
![terminal-backspace](https://github.com/eclipse-cdt/cdt/assets/928116/fa2583b8-b156-4da1-8a3d-85da0218f82c)

**Comment by mlocati** [comment]
Just a side note: with the current version of TM Terminal (11.1.0.202212091724), WLS isn't affected by this issue (that is, pressing the backspace key only deletes one character and not the whole word).

I've tried both executing `bash.exe` from already open "cmd.exe" and "pwsh.exe" TM Terminal views, and from a TM Terminal view opened directly with "C:\WINDOWS\System32\wsl.exe" (and argument "--distribution Ubuntu-22.04").

**Comment by jonahgraham** [comment]
I tested my change on Windows host with cmd, git bash, wsl and ssh to a linux machine running bash and the behaviour of all of them worked well with the unconditional rewrite of `\b` -> `0x7f`.

I need to test still Linux host (and maybe mac if I can get a hold of one) as well as connecting to serial connections and gdb CLI (linux only)

**Comment by mlocati** [comment]
Any update on this? It's a really annoying bug...

**Comment by jonahgraham** [comment]
I have added a fix for this to CDT 11.4.0 due for release in a few weeks.
