### ISSUE TITLE
Rename project does change include directories pointing to this project

### ISSUE THREAD

**Issue by jantje** [eclipse-cdt/cdt#402]
**Describe the bug**
When I rename a managed build project that has a include directory that points somewhere inside the project the include directory does not get updated.

**To Reproduce**
1. Create a managed Build C++ executable project
2. Create the folder include in the source folder
3. Add the src/include folder to the include directories
4. Rename the project
5. The include directories is not updated

**Expected behavior**
The include directories should point to the renamed project not to the old project name.
Note that the actual project folder was renamed so the "include directory" should be updated.
When I try to add the folder again the correct name is provided.

**Screenshots**
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/78b234e4-7137-4e81-90d9-a03f4682cf64)

**Desktop (please complete the following information):**
 - OS: windows

**Additional context**
I was investigating a Sloeber rename issue where I found that the rename failed.
So I thought this must be a CDT issue. 
Managed make did fail but did not rename the include directories.

https://github.com/Sloeber/arduino-eclipse-plugin/issues/1567

**Comment by jantje** [comment]
Update:
The sloeber project rename fails due to a linked folder.
Which I could not yet reproduce in naked managed Build.
So the Sloeber fail is probably unrelated to the include directories not being updated.

**Comment by jonahgraham** [comment]
I cannot reproduce the behaviour you see, but I think the difference is in:

> Add the src/include folder to the include directories

I am not sure what you mean by that exactly. This is how I do it:

![Peek 2023-05-29 12-49](https://github.com/eclipse-cdt/cdt/assets/679236/36d65387-1765-42cf-8dac-ad5cff7d7c32)

which leads to the project name *not* being hardcoded in the settings anywhere and the result in the C/C++ General -> Paths and Symbols being the `${ProjName}`:

![image](https://github.com/eclipse-cdt/cdt/assets/679236/1c53c11a-867c-48ed-90e1-9ad1c73ecf2c)

**Comment by jantje** [comment]
I'm adding the includes in Paths and folders in what I assume is the CDT way not the MBS way.
Both ways seems to result in having the includes at both places.
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/94bf86e1-9452-4c68-aeec-5ae2b44fe5e8)
resulting in a references that does contain the name of the project.
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/502a93d5-7ebf-4ea5-8fdb-7d30c34eb45a)
Which then are not translated during name change.

**Comment by jonahgraham** [comment]
IIUC that is the purpose of the `${ProjName}` variable to solve exactly this kind of problem.

In the C/C++ Build settings pressing Workspace automatically uses  `${ProjName}` as shown below, perhaps the same feature is needed in this dialog to make it easier for users to do the right thing:

https://github.com/eclipse-cdt/cdt/blob/7c8bb9f00ef0d5e3ff493bc0c944519a3e476da2/core/org.eclipse.cdt.ui/utils.ui/org/eclipse/cdt/utils/ui/controls/FileListControl.java#L312-L314

https://github.com/eclipse-cdt/cdt/blob/7c8bb9f00ef0d5e3ff493bc0c944519a3e476da2/core/org.eclipse.cdt.ui/utils.ui/org/eclipse/cdt/utils/ui/controls/FileListControl.java#L325-L331

where PROJECTNAME_PATH is:

https://github.com/eclipse-cdt/cdt/blob/7c8bb9f00ef0d5e3ff493bc0c944519a3e476da2/core/org.eclipse.cdt.ui/utils.ui/org/eclipse/cdt/utils/ui/controls/FileListControl.java#L490-L493

**Comment by jonahgraham** [comment]
#405 provides a workaround kind of fix by avoiding using the project name in the project settings in the first place, instead using `${ProjName}` in the same way as Build Settings for includes and similar settings.

More could be done by adding additional checks in the rename rehandler to identify places like this that the rename could apply to.
