### ISSUE TITLE
CMake project: CompilerBuiltinsDetector does not work for msys2 gcc compiler

### ISSUE THREAD

**Issue by ghentschke** [eclipse-cdt/cdt#407]
When using the gcc/g++ compiler from [MSYS2](https://www.msys2.org/) on Windows 10 in a CMake project, the CompilerBuiltinsDetector cannot fetch the builtins by running the compiler and gathering the results. The line handed to `org.eclipse.cdt.jsoncdb.core.participant.builtins.OutputSniffer.processLine(String)`  is an empty string, because the output buffer is empty. 
The process exit value is 1, but 0 is expected in `org.eclipse.cdt.jsoncdb.core.internal.builtins.CompilerBuiltinsDetector.detectBuiltins(IProject, Path, ICommandLauncher, IConsole, IProgressMonitor)`:
```java
if (state != ICommandLauncher.COMMAND_CANCELED) {
try {
	// check exit status
	final int exitValue = proc.exitValue();
```
Has anybody an idea what the return value of 1 mean? What I've seen so far is, that this value comes from the `Java_org_eclipse_cdt_utils_spawner_Spawner_waitFor` function. This is a C function in `/org.eclipse.cdt.core.native/native_src/win/Win32ProcessEx.c`. The return value comes from this function: [GetExitCodeProcess](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess#return-value)
I cannot find a description for 1 as value of  `lpExitCode`.

When I use the `clang` compiler in the CMakeList.txt from MSYS2 it works:
```txt
set(CMAKE_C_COMPILER "clang")
set(CMAKE_CXX_COMPILER "clang++")
```
1. Windows machine with MSYS2 and cmake and gcc installed
2. Add bin folder of MSYS2 installation to PATH user environment variable.
3. Create a new CMake project in CDT
4. Build it
5. See that the system inlcudes cannot be resolved (similar to #376)
![image](https://github.com/eclipse-cdt/cdt/assets/123444711/028c12d3-ff78-45b1-8f49-613cee389f79)

**Expected behavior**
The CompilerBuiltinsDetector  fetches the system includes from the compiler call: e.g.
```txt
C:/msys2/msys64/mingw64/bin/cc.exe -E -P -dM -Wp,-v C:\TR\workspaces\runtime-cdt-development\Cmk1\build\cmake.debug.win32.x86_64\detect_compiler_builtins.cpp
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version 21H2

**Comment by 15knots** [comment]
Did you install cmake in your MSYS2? If so, that might be the cause of this issue.
MSYS2 cmake generates msys specific paths (/usr/bin/cc) instead of C:/msys2/msys64/mingw64/bin/cc causing CompilerBuiltinsDetector to call a non-existen cc.exe.
Check the cmakecache.txt file for the paths.

I would recommend to install the windows version from cmake.org and make sure that it is in %PATH% before the location of the msys tools (C:/msys2/msys64/mingw64/bin) in your case.

**Comment by ghentschke** [comment]
> Check the cmakecache.txt file for the paths.

I checked it and they were correct. I can build a cmake project. That's not the problem. 

I tried out the cmake for Windows binary from cmake.org as well. I could not build with this version, since this cmake uses this path for the compiler: /mingw64/bin/gcc.exe

**Comment by ghentschke** [comment]
I found out the reason. The gcc.exe from mingw64 (part of Msys2) on Windows needs the bin folder to be on the PATH to be executed. e.g. 'C:\msys64\mingw64\bin' must be part of the PATH environment variable. This can be fixed in `org.eclipse.cdt.jsoncdb.core.internal.builtins.CompilerBuiltinsDetector.getEnvp()` which is called from `org.eclipse.cdt.jsoncdb.core.internal.builtins.CompilerBuiltinsDetector.detectBuiltins(IProject, Path, ICommandLauncher, IConsole, IProgressMonitor)`
