### ISSUE TITLE
Possible deadlock and Eclipse freeze with first Core Build project in fresh Workspace.

### ISSUE THREAD

**Issue by ewaterlander** [eclipse-cdt/cdt#424]
I have created a plugin based on Core Build Makefile project. A project uses the GCC standard toolchain and a custom toolchain.

When creating a first new project in a fresh empty workspace Eclipse regularly  hangs. First the indexer hangs at 0%. Eclipse is still responsive. Menus can be opened. When I click to unfold the project in the project explorer Eclipse goes in a total freeze.

After killing Eclipse and starting again in the same workspace, the problem is gone. The project was not created, but I can now recreate it without problems. Any next project in the workspace does not have the problem.

If I create first another type of project, the problem is not there.

The problem is timing dependent. When I disable the setting Project >> Build Automatically, the problem happens less frequent. Running Eclipse from a development environment also has an impact, then the problem doesn't happen with Build Automatically disabled. The standard CDT Core Build Makefile project does not show the problem.

 - OS: Linux
 - Version CDT 10.5 with some fixes present in 11.x.

The indexer process gets a lock on the HashMap 'configs' in CBuildConfigurationManager.getBuildConfiguration(IBuildConfiguration buildConfig).  Several other processes are also trying to get a lock on the HashMap. This blocks the whole system.
It is triggered by several parallel calls to the AdaptorFactory, getting the CBuildConfiguration from the IBuildConfiguration via IAdaptable.getAdapter().

Note. There was previous bug related to a deadlock on the same HashMap: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540085

**Comment by ewaterlander** [comment]
I found the cause.
There is a possible loop in CBuildConfigurationManager.getBuildConfiguration(IBuildConfiguration buildConfig), that depends on if the build container exists.

In my plugin I put the default buildcontainer to the project directory. At creation of my Core BuildConfiguration I run setBuildContainer(getProject());

CBuildConfiguration.getBuildContainer() assumes the build container is not the project directory, but build/default. If the subfolders do not exist they will be created.

Depending if some process already called CBuildConfiguration.getBuildContainer(), the directories were present or not.
I could fix my deadlock by overriding CBuildConfiguration.getBuildContainer().

Actually there is a TODO in CBuildConfiguration.getBuildContainer() to make the build container a project property. This would solve the problem properly. Even then there is still a theoretical possibility for deadlock if for some reason the build container folders do not exist in time.

This is the loop that can cause the deadlock. If the core build configuration doesn't exist yet it is created via the provider. If then the build container folders do not yet exist there will be loop.

```
CoreBuildLaunchBarTracker.setActiveBuildConfig().run
-> CBuildConfigurationManager.getBuildConfiguration()  <--|
   lock on config                                         |
   -> provider.getCBuildConfiguration()                   |
   CBuildConfiguraton.getBuildContainer()                 |
   Folder.Create()                                        |
   Workspace.endOperation()                               |
   NotificationManager                                    |
   CModelManager                                          |
   CModelListener                                         |
   DeltaAnalyzer                                          |
   CContainer                                             |
   SourceRoot                                             |
   CModelManager.getBinaryFile()                          |
   CModelManager.getBinaryParser()                        |
   -> config.getAdapter(ICBuildConfiguration.class)       |
   -> CBuildConfigurationManager.getBuildConfiguration() -|
```

**Comment by jonahgraham** [comment]
That is interesting analysis - looks like quite a complicated interdependency. I look forward to a possible PR ;)

**Comment by ewaterlander** [comment]
I will work on a PR. :)

**Comment by ewaterlander** [comment]
My first hint was that during the freeze the build folders were not created yet.
Now I see that the deadlock already occurs before I set the build container to the project container in my plugin.
The constructors of StandardBuildConfiguration run applyProperties(), which will end up at CBuildConfiguration.getBuildContainer() which will start the Folder.create which leads to the deadlock.
I added one applyProperties() myself in PR #167

I will remove the build container folder creation from the loop and move it to the start of the build process. This also leaves room for the CBuildConfiguration constructors to change the build container.

**Comment by ewaterlander** [comment]
Here is a full trace that shows that a Folder.create during project creation can trigger a loop back to CBuildConfigurationManager.getBuildConfiguration()  (CDT 10.5). In this debugger trace it was the Change Build Configuration thread. Multiple threads can trigger this loop. During a freeze I see it is mostly the C/C++ Indexer thread.

![deadlock_loop_part1](https://github.com/eclipse-cdt/cdt/assets/102143930/55774f29-bf03-4365-a494-b0935f03beb3)

![deadlock_loop_part2](https://github.com/eclipse-cdt/cdt/assets/102143930/87d311b4-98b9-41a5-815f-b4445c14928c)
