### ISSUE TITLE
Import memory window is not working as expected

### ISSUE THREAD

**Issue by Cosminbyc** [eclipse-cdt/cdt#449]
**Describe the bug**
When click on "Browse" button from "Import memory" window for Plain Text, RAW Binary and SRecord format, it opens "Choose memory import file" window with "Save" button and a "Confirm save as" pop-up.

**Expected behavior**
"Save" button should be replaced with "Open" button and when click "Open" button to not show "Confirm save as" pop-up.

**Screenshots**
![import](https://github.com/eclipse-cdt/cdt/assets/108365301/859802c3-782d-46ab-a981-e02d307c1b3b)

![Confirm_save_as](https://github.com/eclipse-cdt/cdt/assets/108365301/c9aa4680-5731-4741-810f-75ec2a507775)

**Desktop (please complete the following information):**
 - OS: Windows 10

Build Identifier:

 - Eclipse version: 2021-06 (4.20.0)
 - Build id: 20210612-2011

**Comment by jonahgraham** [comment]
Thanks @Cosminbyc for the report. 

@ruspl-afed I was wondering if you had time to look at this issue because IIRC you recently(ish) were working in this area of code.

**Comment by ruspl-afed** [comment]
The error seems to be so old that it could be called a feature. Please have a look at #450 @jonahgraham
