### ISSUE TITLE
Compilation Database Parser: Path must include project and resource name: /ProjectName

### ISSUE THREAD

**Issue by kuch3n** [eclipse-cdt/cdt#452]
**Describe the bug**

Can't set path to `compile_commands.json`

`${ProjDirPath}/ProjectName/_build/Debug/compile_commands.json` 
`{ProjDirPath}/_build/Debug/compile_commands.json`
`C:/cool/full/path/compile_commands.json`

Project with ProjectName is indeed not in Pathname

Also put build files into an additional subdirectory named ProjectName, same error

**To Reproduce**
Set path in settings

**Expected behavior**
Just take the path or use an relative Path from the beginning, e.g. `./build/Debug/compile_commands.json`

**Screenshots**
![grafik](https://github.com/eclipse-cdt/cdt/assets/977721/d784f617-e61e-45c2-8df4-65433457b260)

**Additional context**
Using cmake4eclipse

**Comment by 15knots** [comment]
CDT cmake core build does not allow to configure the path, neither does cmake4eclipse's CMake Compilation DB parser.
This is not a CDT issue. it has been resolved in [cmake4eclipse](https://github.com/15knots/cmake4eclipse/issues/174).

**Comment by jonahgraham** [comment]
Thanks @15knots - I'll close this now.

@kuch3n if you are up to date with latest CDT + cmake4eclipse and you still experiencing problems, please provide some additional details.

**Comment by kuch3n** [comment]
I'll have to crate an interface to support a custom compiler (chc12) see https://github.com/15knots/cmake4eclipse/issues/185. Hence ticket can be kept closed

Software versions in use:
- cmake4eclipse 4.0.2
- CDT 11.2.0
