### ISSUE TITLE
C/C++Testing: XML parse error when using Boost Test Runners (<Context> is not accepted)

### ISSUE THREAD

**Issue by HW-SW** [eclipse-cdt/cdt#459]
**Describe the bug**
In out project we use BOOST test environment for unit and integrationtests. We have defined a "Run Configuration" in eclipse and choose "Boost Test Runner" as "Testrunner". We use data test cases (BOOST_DATA_TEST_CASE_F) in a unit test. When using the boost test runner in eclipse the following error will be reported in "C/C++ Unit"-section:

**XML parse error: Invalid XML format: Element "Context" is not accepted!**

The following program arguements are set in run configuration of boost test runner: "--output_format=XML --log_level=all --report_level=no --"

**To Reproduce**
1. Use/Write any data set test case in boost
2. Run this testcase with "boost test runner" configuration

**Expected behavior**
The boost data testcase are runable when calling them by standard "C/C++ Application" (.../Verification.exe). We expect that eclipse can handle XML-Element `<Context>`

**Screenshots**
![image](https://github.com/eclipse-cdt/cdt/assets/137898405/ca57e9d2-2598-49f7-84ad-083c41cadf22)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser chrome
 - Version 

**Smartphone (please complete the following information):**
 - Not relevant

**Additional context**
In the following screenshot from xml file you can see the` <Context>`-Element due to data test case:
![image](https://github.com/eclipse-cdt/cdt/assets/137898405/97a9ea5f-435e-4101-8272-3f749b28970c)

**Comment by jonahgraham** [comment]
Hi @HW-SW - Thanks for the bug report. It looks like the [code](https://github.com/eclipse-cdt/cdt/blob/7c8bb9f00ef0d5e3ff493bc0c944519a3e476da2/testsrunner/org.eclipse.cdt.testsrunner.boost/src/org/eclipse/cdt/testsrunner/internal/boost/BoostXmlLogHandler.java) that parses the XML from Boost needs updating. As you have observed there is no support for the Context tag. New tests need to be written for the expanded formats in the [testcase](https://github.com/eclipse-cdt/cdt/blob/7c8bb9f00ef0d5e3ff493bc0c944519a3e476da2/testsrunner/org.eclipse.cdt.testsrunner.tests/src/org/eclipse/cdt/testsrunner/testsrunners/BoostTestCase.java).

To do this, someone needs to provide a small, but complete, boost xml file. @HW-SW can you do that?

**Comment by jonahgraham** [comment]
Best as I can tell the contexts are documented in [the help here](https://www.boost.org/doc/libs/1_82_0/libs/test/doc/html/boost_test/test_output/test_tools_support_for_logging/contexts.html) - but it would be useful to know how Context should translate to the Eclipse UI too.

**Comment by HW-SW** [comment]
Hi @jonahgraham ,
thank you very much for your answer and sorry about the late response from my side.

I append you the prepared (the non-context-testcase have been removed to made xml file more readable) xml-file of the test output. [Prepared_report_test.txt](https://github.com/eclipse-cdt/cdt/files/12158764/Prepared_report_test.txt) (Uploaded as txt-file because xml-file was not allowed.)

> but it would be useful to know how Context should translate to the Eclipse UI too. 

Currently the Eclipse UI will translate one data test case to "_0", see the following image:
![image](https://github.com/eclipse-cdt/cdt/assets/137898405/97be89ed-d46b-43d6-a9ba-6e189cfb86e3)
In addition it would be perfekt if the value of inserted test-data will be displayed behind"_0" like "[ inserted data-test-value]".

Example:
The follwowing testcase will use a dataset (`std::array<uint32_t, 4> testData = {0U, 1U, 2U, 3U};`) as input values for test.
`std::array<uint32_t, 4> testData = {0U, 1U, 2U, 3U};
BOOST_DATA_TEST_CASE_F(Fxt_Diagnostics, UNIT_NtcDiagnoseFullScaleMin, testData, val)
{
...
}`

The test result should be display like this:
_+**_ARRAY_INDEX_**+[ val = _**VALUE_OF_ELEMENT_AT_ARRAY_INDEX**_ ] (_TIME_)
_0 **[val = 0]** (_time_)
_1 **[val = 1]** (_time_)
_2 **[val = 2]** (_time_)
_3 **[val = 3]** (_time_)

What do you think about that suggestion?


Thank you very much!

**Comment by jonahgraham** [comment]
That sounds good - I have a prototype that I think addresses what you are asking.

![image](https://github.com/eclipse-cdt/cdt/assets/679236/6db5a4e7-a297-43f9-9282-3eb6c6406e9a)

which seems the best I can do with the XML file you provided and the limitations on the UI today.

There is an assumption in my prototype that I don't feel particularly comfortable with yet. The context of the first Info/Warning/Error message is assumed to the context of the whole TestCase which seems wrong to me, but does work with the use case you provided. But I don't know if your use case is typical. .e.g The full context information is attached to the individual Info/Warning/Error message like this in the detailed side:

![image](https://github.com/eclipse-cdt/cdt/assets/679236/9cd55c63-7d35-4171-b88a-e2bdf4c08348)

Is this a valid assumption, or an over simplification?

PS The context info in the tree is limited to 50 characters as I assume that sometimes the context could be very very long. The full context remains available in the details regardless

A PR for my work to date will be linked from this issue momentarily.

**Comment by HW-SW** [comment]
Hi @jonahgraham ,

what a great message! Thank you so much for your support and prototype.

For my use case your implementation/result is very good and absolutely sufficient!! 

I am not sure if I understood your execution correctly, nevertheless here is an attempt of an answer:
In my previous context tests the input was always a structure of simple data types. But I believe that there is also the possibility to pass complex objects into a context test as input. If I have understood this correctly, your fix could then come to the limits?

Thank you!

**Comment by jonahgraham** [comment]
> If I have understood this correctly, your fix could then come to the limits?

Yes - that's right. My fix *should* mean that it will display something and no longer have an internal error on seeing `Context` in the unit test results. If you find additional cases of context that are displayed in a confusing way, please file new bug reports

For now I will merge this.
