### ISSUE TITLE
Backspace in Local Terminal (cmd.exe) delete the whole word

### ISSUE THREAD

**Issue by I1ario** [eclipse-cdt/cdt#476]
**Describe the bug**
When I open a Terminal Tab and select the Local terminal (cmd.exe), whenever I type a command and try to delete the last character, the entire word gets deleted instead. 
The backspace key behaves like ctrl + backspace.

**To Reproduce**
1. Open a Terminal ( Ctrl + Alt + Shift + T )
2. Select "Local Terminal"
3. Write a command (for example "mvn clean")
4. Use Backspace key
5. Will be deleted last word (for example "clean")

**Expected behavior**
The expected behavior is that I delete the last character (for example "n")

**Version Information (please complete the following information):**
 - Windows 11 Pro (22H2)
 - Eclipse Version 2023-06 (4.27)
 - CDT Version 11.2.0 (Build id: 20230605-1917)

**Comment by jonahgraham** [comment]
Thank you @I1ario for taking the time to create a bug report. This issue has recently been identified and there is a possible fix that hasn't been released yet. Please follow #392 for updates as I will mark this issue as a duplicate.
