### ISSUE TITLE
xpm not found

### ISSUE THREAD

**Issue by AndrewFrank-zxy** [eclipse-cdt/cdt#481]
**Describe the bug**
I installed xpm globally (node global path is on D drive, defined in system path), installed xpack-qemu and xpack-arm-gcc manually, path is in appdata/roaming/xpack/... , when I create a new qemu xpack project in eclipse cdt, it prompts that xpm is not a valid command, and typing echo %PATH% in the built-in terminal shows the old system path.

**To Reproduce**
1. installed xpm globally
2. installed xpack-qemu and xpack-arm-gcc manually
3. create a new qemu xpack project in eclipse cdt

**Version Information (please complete the following information):**
 - windows11
 - Eclipse 2023-06-R
 - CDT11.2.0

**Comment by jld01** [comment]
Please raise this issue with the Eclipse Embedded CDT project: https://github.com/eclipse-embed-cdt/eclipse-plugins

**Comment by AndrewFrank-zxy** [comment]
thanks.
