### ISSUE TITLE
Memory Search GUI improvement 

### ISSUE THREAD

**Issue by LizzMre** [eclipse-cdt/cdt#515]
**Describe the issue**
Selecting a memory address from the memory search results list does not refocus on Memory Browser/ Memory view. 

**To Reproduce**
1.	Open “Memory Browser” or “Memory view”. 
2.	Open the context menu and select “Find and Replace”. 
3.	Add value to the “Find” field and then click on “Find All”. 
4.	“Search” view will be opened in the same tab group as the memory view. 
5.	Click on a memory address.

**Expected behavior**
Focus on Memory Browser/ Memory view and jump to the selected memory address.

**Potential Fix**
Improve selection changed listener implementation: https://github.com/eclipse-cdt/cdt/blob/main/memory/org.eclipse.cdt.debug.ui.memory.search/src/org/eclipse/cdt/debug/ui/memory/search/MemorySearchResultsPage.java#L172.  

**Additional context**
The current behavior does not include refocusing on the memory views, thus it is not intuitive for the user that selecting an address from the memory search result list has any effect. 
To see the effect, the user must switch to the memory views manually.

**Comment by LizzMre** [comment]
Here you can find my proposed solution: https://github.com/LizzMre/cdt/commit/3c792b18bddcdfe882028b3f6c6abade29bcf329

**Comment by jonahgraham** [comment]
> Here you can find my proposed solution: https://github.com/LizzMre/cdt/commit/3c792b18bddcdfe882028b3f6c6abade29bcf329

Can you make a PR with that change so it can be reviewed?

**Comment by jonahgraham** [comment]
PS Please merge or rebase you change on the main branch  - I just merged some fixes to the build reporting.
