### ISSUE TITLE
Headless build ignores project dependencies and builds projects in random order

### ISSUE THREAD

**Issue by trancexpress** [eclipse-cdt/cdt#528]
**Describe the bug**
When running a headless build, project references are ignored. Projects are built in a random order, potentially running into compile errors due to not built dependency projects.

**To Reproduce**
1. Unpack attached projects somewhere: [example_projects.zip](https://github.com/eclipse-cdt/cdt/files/12454363/example_projects.zip)
2. Use latest Eclipse CDT to compile in headless mode:
```
.../CDT_testing/eclipse/eclipse -vm /usr/lib/jvm/java-17/bin/java --launcher.suppressErrors -data  /tmp/tmpworkspace  -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -importAll .../CDT_testing/workspace/ -cleanBuild all
```
3. Observe project `Test2` is built before project `Test1`, despite the reference of `Test2` to `Test1`.
4. Start Eclipse CDT, import the two projects, observe that `Test1` is built first. The project that is referred to, is built first, as expected.

**Expected behavior**
Build order depends on project references, instead of being random.

**Version Information (please complete the following information):**
 - OS and OS Version/extra details:
Linux, RHEL 7.9
 - Eclipse Version from Help -> About
 ```
Eclipse IDE for C/C++ Developers (includes Incubating components)
Version: 2023-06 (4.28.0)
Build id: 20230608-1333
```
 - CDT Version from Help -> About -> Installation Details -> Features tab
 ```
C/C++ Development Tools
Version: 11.2.0.202306051917
Build id: 20230605-1917
Copyright (c) 2002, 2023 Contributors to the Eclipse Foundation
```

**Additional context**
There seems to be a hash map here, that "determines" the build order:

https://github.com/eclipse-cdt/cdt/blob/72c8186f5084461b6165f94670903dc9d74296dd/build/org.eclipse.cdt.managedbuilder.core/src/org/eclipse/cdt/managedbuilder/internal/core/HeadlessBuilder.java#L314C30-L314C30

**Comment by jonahgraham** [comment]
Is this a regression?

**Comment by jonahgraham** [comment]
I don't understand (on a very cursory inspection) why this is a headless build issue and not a universal issue.

Are you hoping to get this fix in 11.3 (which RC1 was supposed to be today)?

**Comment by trancexpress** [comment]
> Is this a regression?

Not that I'm aware of, I'll check how older CDT versions behave / how older CDT code looks like.

Users of our product complained that their setup no longer compiles in headless mode, due to a different order of compilation for their projects. We updated to JRE 17 and so the hash map in headless builder results in a different order.

Unfortunately I didn't find a workaround, other than invoke the headless build multiple times with subsets of projects, so that dependencies are built first. Which is not great.

**Comment by jonahgraham** [comment]
Since it isn't likely to be a regression I don't think the fix will make it into 11.3.0 (aka today's build).

Lets continue working together to get this solved.

**Comment by jonahgraham** [comment]
@umairsair I was wondering if you have experience in this area and could comment? I am hoping so based on your recent work fixing other aspects of the headless builder (e.g. #388).

**Comment by umairsair** [comment]
There were some ordering issues but those were fixed under https://bugs.eclipse.org/bugs/show_bug.cgi?id=546407. My understanding is that if CDT configuration references are properly set then there should be no issue.

**Comment by trancexpress** [comment]
> There were some ordering issues but those were fixed under https://bugs.eclipse.org/bugs/show_bug.cgi?id=546407. My understanding is that if CDT configuration references are properly set then there should be no issue.

They are, in the IDE. Not during the headless build. Or am I missing something here?

**Comment by umairsair** [comment]
We can close it unless @trancexpress thinks otherwise.

**Comment by trancexpress** [comment]
Will re-open if for some reason the setting doesn't work for users. But for now, I think yes, we should close this.

Thanks for the help!
