### ISSUE TITLE
CDT 11.3 does not have BREE header in MANIFEST.MF, uses Require-Capability, causes false positive API Compatibility errors

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#551]
Perhaps as a result of updating Tycho upgrade the CDT 11.3 manifests publish with:

```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=17))"
```

automatically converted from BREE:

```
Bundle-RequiredExecutionEnvironment: JavaSE-17
```

This leads to false positive API errors like this:

`
2023-09-13T22:28:04.9985777Z [API ERROR] File MANIFEST.MF at line 5: The minor version should be incremented in version 8.3.0, since execution environments have been changed since version 8.3.0 (location: /home/runner/work/cdt/cdt/core/org.eclipse.cdt.core/META-INF/MANIFEST.MF)
`

**Comment by jonahgraham** [comment]
I suspect the easiest thing short term is to add API filters for this error, but I need to track this back to Tycho and/or PDE to resolve fully.

**Comment by akurtakov** [comment]
This is PDE issue for sure as BREE is deprecated by OSGi for years although PDE never made the move.

**Comment by Kummallinen** [comment]
@jonahgraham Looking at the differences in the CDT pom & my local ones, I think the difference causing this is I have "<deriveHeaderFromSource>false</deriveHeaderFromSource>" in the tycho-compiler-plugin configuration. See https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#new-parameter-in-tycho-packaging-pluginpackage-plugin

**Comment by jonahgraham** [comment]
The final resolution of this:

- Create an unpublished (so far) CDT 11.3.1 that has the BREE fixed (#553)
- Use that URL for api baseline instead of latest when preparing for 11.4 dev #554 

Last question, should we publish 11.3.1 fully (i.e. add it to https://download.eclipse.org/tools/cdt/releases/11.3/ composite) or just add a note as to why it is excluded. My current preference is the latter, but I am open to suggestions!

**Comment by Kummallinen** [comment]
I'd vote for not publishing 11.3.1 and just adding a note. Future updates will still work so there doesn't seem to be any need to cause an extra update for users.

**Comment by jonahgraham** [comment]
Done in 78e15207f24770e01d28cb5e922fc40eead58816 and https://ci.eclipse.org/cdt/job/promote-files-to-download/ has been run to copy the files to https://download.eclipse.org/tools/cdt/releases/11.3/
