### ISSUE TITLE
CDT does not detect installations of the MSYS2 UCRT64 toolchain

### ISSUE THREAD

**Issue by jld01** [eclipse-cdt/cdt#568]
The MSYS2 project suggests that new users install an MSYS2 UCRT64 [environment](https://www.msys2.org/docs/environments/) if they are unsure of their requirements.

At present, CDT detects MSYS2 installations of the MINGW64 and MINGW32 toolchains but does not detect the UCRT64 toolchain variant.

We should enhance the toolchain detection logic to locate UCRT64 toolchains to ensure a good experience for new users. At present, CDT looks for MinGW toolchain installations in a certain order and uses the first installation it finds by default. To preserve behaviour of existing projects, we should therefore look for toolchains in the order: MINGW64, MINGW32, UCRT64

Users can override the default toolchain selection at system, workspace or build configuration level using the MINGW_HOME environment variable.

**Comment by jonahgraham** [comment]
Thanks @jld01 for keeping CDT up to date with the ever changing landscape of gcc on Windows.
