### ISSUE TITLE
CDT 11.2.0, "enum class XXX xxx"  as function parameters is identified as CPPASTProblemDeclaration

### ISSUE THREAD

**Issue by edisonluo0501** [eclipse-cdt/cdt#590]
**Describe the bug**
This declaration code: "PMSErrorcode HandleCreateOrDeleteConfig(enum class EnConfigOperType operType); " is identified as CPPASTProblemDeclaration, but the compiler can compile and pass. In addition, all similar "enum class XXX xxx"  as function parameters are identified as CPPASTProblemDeclaration in my project.

**To Reproduce**
1. Import project
2. MyAstChecker extends AbstractIndexAstChecker
3. Some declaration code like problem description in cpp file
4. See problem description

**Expected behavior**
The problem description can be correctly identified as a function declaration.

**Screenshots**
![image](https://github.com/eclipse-cdt/cdt/assets/147576491/04ad1371-179d-4cd7-8624-f0e5d45747d8)

**Version Information (please complete the following information):**
 - OS and OS Version/extra details: Linux
 - Eclipse Version from Help -> About 2023-06, 4.28
 - CDT Version from Help -> About 11.2.0

**Comment by i-garrison** [comment]
Hi @edisonluo0501 can you please provide code example as text? Currently I get this from GCC `error: use of enum 'UndefinedEnumClass' without previous declaration`

**Comment by edisonluo0501** [comment]
> Hi @edisonluo0501 can you please provide code example as text? Currently I get this from GCC `error: use of enum 'UndefinedEnumClass' without previous declaration`

I'm sorry my project code can't be shared, but I can provide a simple example as:
![image](https://github.com/eclipse-cdt/cdt/assets/147576491/8dd1a183-845a-47a3-9596-3317013f1513)
where the compiler can compile, but there's a warning like this:
**warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword.**

Please check whether the problem needs to be rectified.

**Comment by i-garrison** [comment]
Sorry cannot copy from images. Could you please prepare *text* of minimal self-contained example (i.e. just single c++ source file, without any includes and external references)?

**Comment by edisonluo0501** [comment]
> Sorry cannot copy from images. Could you please prepare _text_ of minimal self-contained example (i.e. just single c++ source file, without any includes and external references)?

this is all the code in test.cpp

------------------------
#include <iostream>
using namespace std;
enum class A {
	B,
	C
};
void func(enum class A a) {
	cout << "value is:" << static_cast<int>(a) << endl;
}
int main() {
	return 0;
}

----------------
no any other any includes or external references

**Comment by i-garrison** [comment]
Well that does not compile, and if I fix errors `clang` complains:
```
# clang++ -fsyntax-only test.cc
test.cc:5:16: error: reference to enumeration must use 'enum' not 'enum class' [-Welaborated-enum-class]
    5 | void func(enum class A a) {
      |                ^~~~~
```
You probably need to replace `enum class` with `enum` in those locations.

**Comment by edisonluo0501** [comment]
> Well that does not compile, and if I fix errors `clang` complains:
> 
> ```
> # clang++ -fsyntax-only test.cc
> test.cc:5:16: error: reference to enumeration must use 'enum' not 'enum class' [-Welaborated-enum-class]
>     5 | void func(enum class A a) {
>       |                ^~~~~
> ```
> 
> You probably need to replace `enum class` with `enum` in those locations.

Well, my job is to process a lot of code with CDT AST to get call relationships. The result shows that a small amount of code like problem described, I cannot modify these codes because which is written by others. Now, if the code like problem described is not identified correctly, the resulting data I processed will be lost. If you don't want to deal with this situation, forget it.
