### ISSUE TITLE
How does CDT determine whether OpenOCD has been successfully started?

### ISSUE THREAD

**Issue by YuraGakki** [eclipse-cdt/cdt#599]
I used a modified openocd and tried to start openocd for debugging through CDT, but I received a timeout error and the console did not provide any output. But it can be started in the shell with the same commands and parameters. And when I intentionally pass in the wrong parameters to cause my OpenOCD to exit abnormally, the console can output a complete log.

 My OpenOCD will eventually run to the server_loop(), blocked by select(), which is consistent with the official openocd. In my testing, after the CDT called openocd, my openocd did indeed run to the server_loop().

So how does CDT determine whether OpenOCD has been successfully started? Where may the problem be?
Thank you in advance for any comments on this issue!

![1](https://github.com/eclipse-cdt/cdt/assets/60292504/e0f41fda-9202-4182-9244-94d56b1e1e52)
![2](https://github.com/eclipse-cdt/cdt/assets/60292504/d65da46d-278e-4330-b85b-8965a011e68e)
![3](https://github.com/eclipse-cdt/cdt/assets/60292504/ccfe7496-12ca-4994-8200-fcc5eea892e3)

**Comment by YuraGakki** [comment]
The CDT version I am using is 10.7.1 and the openocd version is 0.10

**Comment by YuraGakki** [comment]
Strangely, when openocd runs to the server_loop indicates that it has successfully started and connected to the device, waiting for gdb to communicate with it through the TCP port. At this time, the CDT console has no output and seems to be waiting for openocd to start.

**Comment by YuraGakki** [comment]
In Windows, besides the timeout error, I also received this error message : 

`An internal error occurred during: "Starting OpenOCD".
RequestMonitor: Sequence "", result for executing step #1 = Status ERROR: org.eclipse.cdt.dsf code=10005 Request for monitor: 'RequestMonitor (org.eclipse.embedcdt.debug.gdbjtag.core.dsf.GnuMcuGdbServerBackend$GdbServerStep$1@4a92632b): Status OK: unknown code=0 OK' resulted in a rejected execution exception., done() method called more than once`

![image](https://github.com/eclipse-cdt/cdt/assets/60292504/58a90519-da66-4773-bc9c-6d1a96c40ef6)

There is no such information in Linux.

**Comment by jld01** [comment]
Hi @YuraGakki, it looks like you are using the AndeSight IDE. In that case, the final debug launch sequence will be provided by the IDE vendor based on code provided by the [Eclipse Embedded CDT](https://eclipse-embed-cdt.github.io/) project. I suggest you raise this issue with the IDE vendor in the first instance.

**Comment by YuraGakki** [comment]
> Hi @YuraGakki, it looks like you are using the AndeSight IDE. In that case, the final debug launch sequence will be provided by the IDE vendor based on code provided by the [Eclipse Embedded CDT](https://eclipse-embed-cdt.github.io/) project. I suggest you raise this issue with the IDE vendor in the first instance.

Thanks @jld01 . I only used the OpenOCD provided by Andes, and CDT is still the official CDT. It is only that some UI names have been modified, and the functional code has not been modified. Using another GDB OpenOCD Debugging will result in the same phenomenon.

![image](https://github.com/eclipse-cdt/cdt/assets/60292504/c8831eb8-6690-43ad-89a6-2ec7cb59bc97)

**Comment by jld01** [comment]
If you observe the same issue with the _GDB OpenOCD Debugging_ launch configuration type, then I suggest you raise this as an [issue](https://github.com/eclipse-embed-cdt/eclipse-plugins/issues) with the [Eclipse Embedded CDT](https://eclipse-embed-cdt.github.io/) project. Be sure to mention the exact version of OpenOCD that you are using.

**Comment by jld01** [comment]
Issue raised at https://github.com/eclipse-embed-cdt/eclipse-plugins/issues/593.
