### ISSUE TITLE
Replace dependency to org.eclipse.osgi.services 

### ISSUE THREAD

**Issue by HannesWell** [eclipse-cdt/cdt#650]
The bundle `o.e.osgi.services` is deprecated for removal as part of https://github.com/eclipse-equinox/equinox/issues/18 and already has been changed to be empty and only re-export the 'official' OSGi artifacts published to Maven-Central.
It should be replaced by imports of the desired `org.osgi.service.*` packages so that the runtime can choose a suitable provider independently of the bundle name.

**Comment by ruspl-afed** [comment]
Oops, I forgot that we already have this one and created another #669 , sorry for this @HannesWell 
But now it should be fixed with #670

**Comment by HannesWell** [comment]
> Oops, I forgot that we already have this one and created another #669 , sorry for this @HannesWell But now it should be fixed with #670

No problem and thanks for fixing this.
