### ISSUE TITLE
Enhance PE64 symbol presentation in Project Explorer

### ISSUE THREAD

**Issue by jld01** [eclipse-cdt/cdt#652]
The _Project Explorer_ view presents source file name plus function and data symbols in a hierarchy of child items of an _ELF_ object file as follows:

![image](https://github.com/eclipse-cdt/cdt/assets/45816183/c48af71d-5feb-4cc5-9eb5-a4a363dba08a)

However, for _PE64_ object files, only the function symbols are presented:

![image](https://github.com/eclipse-cdt/cdt/assets/45816183/14f20d23-0a9b-42dc-8943-2299514e0fac)

We should enhance the analysis of PE64 object files to provide a presentation similar to that for ELF object files as far as possible.

**Comment by PatrickTasse** [comment]
Hi John,

This change breaks our unit tests in Trace Compass:
https://ci.eclipse.org/tracecompass/job/tracecompass-gerrit-short-ui-only/4265/testReport/junit/org.eclipse.tracecompass.lttng2.ust.ui.swtbot.tests/FlameChartViewTest/testManipulatingMappingFiles/

The GNUPEParser64 extension has a null config extension reference, causing a NPE.

Do we perhaps have to update our project configuration? Right now we only include org.eclipse.cdt.gnu.dsf.feature.group in our target and have plug-in dependencies on org.eclipse.cdt.core and org.eclipse.cdt.core.native.

Before this change it was executing the base class implementation PEBinaryObject64.loadSymbols().

**Comment by jld01** [comment]
Hi @PatrickTasse, in CDT, we generally obtain information from binary files via a call to [BinaryParserConfig.getBinaryParser()](https://github.com/eclipse-cdt/cdt/blob/dd543580a53c10383f734c2ec50c3031b2a6ab44/core/org.eclipse.cdt.core/model/org/eclipse/cdt/internal/core/model/BinaryParserConfig.java#L46).

The `ICConfigExtensionReference` that is passed to the `BinaryParserConfig` constructor is deduced in [CModelManager.getBinaryParser(IProject)](https://github.com/eclipse-cdt/cdt/blob/dd543580a53c10383f734c2ec50c3031b2a6ab44/core/org.eclipse.cdt.core/model/org/eclipse/cdt/internal/core/model/CModelManager.java#L612). I suggest you step through this method and determine why the `ICConfigExtensionReference` is null in your usage.

I hope this helps.

**Comment by PatrickTasse** [comment]
We get our binary parsers directly from the extension registry, using code that essentially mimics what is done with:

CCorePlugin.getDefault().getBinaryParser(extension.getUniqueIdentifier())

These binary parsers all have a null config extension reference.

In our test we have a file that uses ElfParser, this one still works. Another file (a win32 executable) uses GNUPEParser64, this one was working using this method until now.

**Comment by PatrickTasse** [comment]
The original code is here:

https://git.eclipse.org/c/tracecompass/org.eclipse.tracecompass.git/tree/tmf/org.eclipse.tracecompass.tmf.core/src/org/eclipse/tracecompass/internal/tmf/core/callstack/FunctionNameMapper.java#n269

But I'm considering changing to this, to use a public API instead:

        /* Get all the available binary parsers */
        final List<IBinaryParser> binaryParsers = new ArrayList<>();
        IExtension[] extensions = Platform.getExtensionRegistry().
                getExtensionPoint(CCorePlugin.BINARY_PARSER_UNIQ_ID).getExtensions();
        for (IExtension extension : extensions) {
            SafeRunner.run(new ISafeRunnable() {
                @Override
                public void run() throws Exception {
                    IBinaryParser binaryParser = CCorePlugin.getDefault().getBinaryParser(extension.getUniqueIdentifier());
                    binaryParsers.add(Objects.requireNonNull(binaryParser));
                }

                @Override
                public void handleException(@Nullable Throwable exception) {
                    Activator.logError("Error creating binary parser", exception); //$NON-NLS-1$
                }
            });
        }

**Comment by jld01** [comment]
@PatrickTasse, in #665 I enhanced the `GNUPEBinaryObject64` class to make use of an `IGnuToolFactory` in the same way that the `GNUElfBinaryObject` class does. So `GNUPEBinaryObject64` now requires a valid `ICConfigExtensionReference` for correct invocation of the binutils such as `addr2line` like the `GNUElfBinaryObject` class.

If you are not able to provide an appropriate `ICConfigExtensionReference` in the same way as [CModelManager.getBinaryParser(IProject)](https://github.com/eclipse-cdt/cdt/blob/dd543580a53c10383f734c2ec50c3031b2a6ab44/core/org.eclipse.cdt.core/model/org/eclipse/cdt/internal/core/model/CModelManager.java#L612), then one option would be for you to use `PEParser64` instead of `GNUPEParser64`. This would mirror your use of `ElfParser` rather than `GNUElfParser`.
