### ISSUE TITLE
StringIndexOutOfBoundsException when CMakeListst.txt is missing

### ISSUE THREAD

**Issue by 15knots** [eclipse-cdt/cdt#66]
CDT cmake core build fails to parse the error.

java.lang.StringIndexOutOfBoundsException: String index out of range: -11
    at java.base/java.lang.String.substring(String.java:1841)
    at org.eclipse.cdt.cmake.core.internal.CMakeErrorParser$MessageHandler.processMessage(CMakeErrorParser.java:203)
    at org.eclipse.cdt.cmake.core.internal.CMakeErrorParser.processMessage(CMakeErrorParser.java:126)
    at org.eclipse.cdt.cmake.core.internal.CMakeErrorParser.close(CMakeErrorParser.java:96)

This should produce an error in the problems view instead.

**Comment by jonahgraham** [comment]
Thanks @15knots - BTW as part of the transition to GitHub where issues and PRs are quite similar we [removed requirement](https://github.com/eclipse-cdt/cdt/blob/main/CONTRIBUTING.md#creating-pull-requests) to have issues, instead only recommending them for larger changes. 

Do you think this warrants a 10.7.x release (i.e. backport this change). Or should we wait until next release in Dec?

**Comment by 15knots** [comment]
Am Mittwoch, 7. September 2022, 21:28:38 CEST schrieb Jonah Graham:
> Thanks @15knots - BTW as part of the transition to GitHub where issues and
> PRs are quite similar we [removed
> requirement](https://github.com/eclipse-cdt/cdt/blob/main/CONTRIBUTING.md#c
> reating-pull-requests) to have issues, instead only recommending them for
> larger changes.

OK, I see.

> 
> Do you think this warrants a 10.7.x release (i.e. backport this change). Or
> should we wait until next release in Dec?

Given the fact that no-one ever stumbled into this since 2019 (when I added 
the error parser), I think we could wait until the next release.

BTW: Would it be possible to make the cmake error parser public API? Its code 
is almost  1:1 ported from my MBS plugin and I would like to have only a 
single point where to do bug fixes.

/Martin

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by jonahgraham** [comment]
> BTW: Would it be possible to make the cmake error parser public API? Its code is almost 1:1 ported from my MBS plugin and I would like to have only a single point where to do bug fixes. /Martin

This got answered in another [thread on cdt-dev](https://www.eclipse.org/lists/cdt-dev/msg35308.html) - please let me know if there is more I can do.
