### ISSUE TITLE
*.S files are not preprocessed in managed builds

### ISSUE THREAD

**Issue by kisvegabor** [eclipse-cdt/cdt#666]
**Describe the bug**
`*.S` assembly files are not preprocessed in managed builds

**To Reproduce**

1. Create a new Hello World managed build C project
2. Add `test.S` to the `src` folder
3. Add `nop` to `test.S`
4. Build the project, it works
5. Change the content of `test.S` to
```c
#ifdef MY_ASM_ENABLE
some_invalid_asm_instruction
#endif
```
6. Build the project, now it fails with
```
../src/test.S:2: Error: no such instruction: `some_invalid_asm_instruction'
make: *** [src/subdir.mk:31: src/test.o] Error 1
```
despite of `MY_ASM_ENABLE` is not defined, so `some_invalid_asm_instruction` should be ignored

**Expected behavior**
Preprocess `*.S` files

**Screenshots**
![image](https://github.com/eclipse-cdt/cdt/assets/7599318/0479cb5f-58b7-472f-9872-1ad8951aeb07)

**Version Information (please complete the following information):**
 - OS and OS Version/extra details: Linux Mint (LMDE 5)
 - Eclipse Version from Help -> About: 2023-12 (4.30.0)
 - CDT Version from Help -> About -> Installation Details -> Features tab: 11.4.0

**Additional context**
I could workaround the problem by adding `*.S` as C source file:
![image](https://github.com/eclipse-cdt/cdt/assets/7599318/f80a09d4-cd57-41b7-b71f-16f4e403d455)

**Comment by jld01** [comment]
Hi @kisvegabor, GNU `as` does not invoke the C preprocessor. In order to pre-process your `test.S` file, you will need to use `gcc` as the assembler _Command_ and add `-c` to the _Assembler flags_ option:

![image](https://github.com/eclipse-cdt/cdt/assets/45816183/368f11ec-c927-4816-93cc-484820b2b607)

@jonahgraham and @Torbjorn-Svensson, we should discuss making this the default behaviour.

**Comment by kisvegabor** [comment]
It's cleaner solution, thank you! 

As far as I know `*.s` (lower case) files should not be preprocessed. Will `gcc` make a decision based on the extension?

**Comment by jld01** [comment]
> As far as I know `*.s` (lower case) files should not be preprocessed. Will `gcc` make a decision based on the extension?

Yes.

**Comment by kisvegabor** [comment]
Great, thank you John!

**Comment by Torbjorn-Svensson** [comment]
> > As far as I know `*.s` (lower case) files should not be preprocessed. Will `gcc` make a decision based on the extension?
> 
> Yes.

Hm. @jld01, do you have any reference where it states that `gcc` will make a difference on `*.s` and `*.S` regarding if preprocessing the content is performed or if the content is sent directly to `as`?

**Comment by jonahgraham** [comment]
@Torbjorn-Svensson I think that [this doc](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html) covers it, quoted:

> For any given input file, the file name suffix determines what kind of compilation is done:
> ...
> 
> **file.s**
>   Assembler code.
> 
> **file.S**
> **file.sx**
>   Assembler code that must be preprocessed.

This can be manually set with `-x language` where language is assembler or assembler-with-cpp

**Comment by Torbjorn-Svensson** [comment]
> @Torbjorn-Svensson I think that [this doc](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html) covers it, quoted:
> 
> > For any given input file, the file name suffix determines what kind of compilation is done:
> > ...
> > **file.s**
> > Assembler code.
> > **file.S**
> > **file.sx**
> > Assembler code that must be preprocessed.
> 
> This can be manually set with `-x language` where language is assembler or assembler-with-cpp

Ah! That explains why our tool preprocesses .s files. Thanks for the clarification!

**Comment by Torbjorn-Svensson** [comment]
> Hi @kisvegabor, GNU `as` does not invoke the C preprocessor. In order to pre-process your `test.S` file, you will need to use `gcc` as the assembler _Command_ and add `-c` to the _Assembler flags_ option:
> 
> ![image](https://private-user-images.githubusercontent.com/45816183/293995031-368f11ec-c927-4816-93cc-484820b2b607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTU4MzcsIm5iZiI6MTcwNDM1NTUzNywicGF0aCI6Ii80NTgxNjE4My8yOTM5OTUwMzEtMzY4ZjExZWMtYzkyNy00ODE2LTkzY2MtNDg0ODIwYjJiNjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA4MDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYmJkMWM4OWZlZjFmNTc2MzI3YmNhMmUyZDRjMzg5YjYwZWU5NDE4ZGU0YTQ5NWFlODcwN2RjYWU2M2IxYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lvS6Y39bkrnKyozWUiQlI7LuHNrrsbt4JYbOZjL0kdo)
> 
> @jonahgraham and @Torbjorn-Svensson, we should discuss making this the default behaviour.

I think it would make sense to use the `gcc` binary instead of `gas` for `*.S` files.

**Comment by jld01** [comment]
It seems there would be a migration issue to consider for existing projects where the assembler _Command_ option has not been modified by the user but the _Assembler flags_ option _has_ been modified. In such cases, the `command` attribute of the assembler `<tool>` element is not present in the `.cproject` file. So the project would use the new assembler _command_ from the revised toolchain description but would _not_ pick up the new `-c` flag. We could probably use an `IOptionDefaultValueGenerator` to avoid this issue.

**Comment by jantje** [comment]
As discussed during the CDT call:
Given that the proposed fix requires a migration which may not be successful for the people who have had (and solved) this issue I ask whether it is smart to do the proposed fix.
Basically there is a known work work around for the CDT provided project types.
Other projectTypes probably do not have this issue.
Given this is about building assembly language files that need the preprocessor to be compiled properly I would expect this to be a rare case.
So I'm wondering: given all the drawbacks of the current proposed fix and given the likely hood of it happening: Is it worth implementing the current proposed fix?

**Comment by kisvegabor** [comment]
It's great that issue was being discussed! 

I can't see the all the details and possible issues, however I can tell my use case in the hope that it helps to make a decision.

We are developing an embedded UI library which now has some `*.S`files for multiple Arm architectures to speed up some critical operations. Mostly we are developing the UI library on PC where the content of the `*.S` files should be disabled by an `#if ...`. 

Generally speaking this issue happens for everyone who adds ASM to speed up some parts of the code on foreign architectures. I don't know how common this use can be.
