### ISSUE TITLE
std::optional is not working on Eclipse 4.30.0

### ISSUE THREAD

**Issue by VietHungPhan** [eclipse-cdt/cdt#675]
std::optional is not working on Eclipse 4.30.0. Please see the screenshot.
![image](https://github.com/eclipse-cdt/cdt/assets/43219867/aaa81469-c2a1-4a2f-9e78-da2cea9a662a)

![Screenshot](https://github.com/eclipse-cdt/cdt/assets/43219867/df80ce8b-0a05-4a58-b592-7bd473e6e219)

Thanks & Regards,
Viet-Hung Phan

**Comment by VietHungPhan** [comment]
We are using Linux GCC for Eclipse.

**Comment by i-garrison** [comment]
Hi @VietHungPhan if you navigate to `optional` header file, do you see that `__cplusplus >= 201703` is true? If not, this is probably due to your GCC version 8 is defaulting to C++14 and you will need to manually add `-std=c++17` to indexer options.

**Comment by VietHungPhan** [comment]
Hi Igor,
Thanks for your advises. I have switched my GCC version from 8 to 13, then it works for me.
BR,Ericsson CanadaViet-Hung Phan

    On Wednesday, January 17, 2024 at 01:56:49 p.m. EST, Igor V. Kovalenko ***@***.***> wrote:  
 
 


Hi @VietHungPhan if you navigate to optional header file, do you see that __cplusplus >= 201703 is true? If not, this is probably due to your GCC version 8 is defaulting to C++14 and you will need to manually add -std=c++17 to indexer options.

**Comment by VietHungPhan** [comment]
Thanks again. It works for me with GCC version 13.2.0.
BR,
Ericsson Canada Inc.
Veit-Hung Phan
