### ISSUE TITLE
It is missing std::optional in Eclipse 2024-03 with GCC version 13.2.0

### ISSUE THREAD

**Issue by VietHungPhan** [eclipse-cdt/cdt#736]
Hi,
I always get the error "Symbol optional could not be resolved" for std::optional in Eclipse 2024-03 with linux GCC version 13.2.0. Below is my codes.
![image](https://github.com/eclipse-cdt/cdt/assets/43219867/e216e51a-aae9-4012-880f-b16697596d8b)

**Comment by i-garrison** [comment]
Looks like your GCC is version 8, see include paths. This could be too low by default, try setting `-std=c++17` or configure CDT to use newer compiler.

**Comment by VietHungPhan** [comment]
Thanks. I have switched to gcc/13.2.0 and it works fine.
BR,Viet-Hung PhanEricsson Canada.

    On Wednesday, March 13, 2024 at 01:36:08 a.m. EDT, Igor V. Kovalenko ***@***.***> wrote:  
 
 


Looks like your GCC is version 8, see include paths. This could be too low by default, try setting -std=c++17 or configure CDT to use newer compiler.
