### ISSUE TITLE
Change the wording for the Code Analysis function BlacklistChecker

### ISSUE THREAD

**Issue by ghost** [eclipse-cdt/cdt#746]
**Is your feature request related to a problem? Please describe.**
In Eclipse CDT Settings Section "Code Analysis" there is a wording for "blacklisted functions", and in my humble opinion it sounds to my ears rather negative for the black color - the black color is here used in a meaning that is exclusively negative - something to block or to forbid, and yes my feeling is that this wording is rather negative for the black color, even if similar wording would be as clear and understandable, like "this function is listed as blocked (i.e. is in a blocklist), or to be used-with-caution", or I think there are many other similar possible wordings;

Please don't see any offense in my request, I find the feature of showing some functions in CDT Editor as blocked or to be used-with-caution very useful, for example if we work with external libraries, it is just the wording that I think we could make better here.

**Describe the solution you'd like**
Replacement of the words which contain "blacklist" with an alternative and equivalent word, for example "is in a blocklist", or "is blocked", or "is to be used-with-caution"

**Describe alternatives you've considered**

**Additional context**
Searching the repository I found the following commit which introduced the Function Checker feature:
https://github.com/eclipse-cdt/cdt/commit/a159173a5152d373c49b0266b744c39d1affe26b
I will try to do the changes of the concerned files myself and then commit the modifications in git and submit a pull request, and I hope it is appropriate to first create the Feature request so that it can be mentioned in the commit comment when the changes will be done;

**Comment by jonahgraham** [comment]
Hi @thomashuber - thank you for raising this. We should definitely fix this to use properly inclusive language. I would happily review a PR on this topic.

In addition we brought this request to the wider Eclipse planning at the Eclipse Architecture Council where we have [started the process](https://wiki.eclipse.org/Architecture_Council/Meetings/Meeting_Notes) of having an Eclipse wide policy and/or guidelines, probably based on resources such as https://inclusivenaming.org/

**Comment by jonahgraham** [comment]
Thank you @thomas-z8 - I merged #794 - but I will leave this open for the fuller version if you have time to work on it.
