### ISSUE TITLE
Future Standalone debugger (cdtdebug.sh) - remove it/other ideas?

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#781]
The Standalone debugger has not worked in installed EPP builds for a while. This is because the way standalone debugger is built requires that the set of bundles available during CDT build matches exactly what is installed in the final product. There keep being problems with that (see recent details in https://github.com/eclipse-cdt/cdt/issues/591 and its referenced PRs)

**Comment by jonahgraham** [comment]
@ruspl-afed made a simplification to the build process in #761 that in the short term may have broken the standalone debugger, but long term may lead to a better solution:

The install script can't find the config.ini because the generator step was removed: If I run the install script I get this:

```sh
$ bash ./install.sh
cp: cannot stat './config.ini': No such file or directory
Installation complete
```

The cdtdebug.sh starts properly, but with the missing config.ini, the loaded UI doesn't prompt for executable and much of the simplification of the UI is missing (i.e. there is too much stuff present)

![image](https://github.com/eclipse-cdt/cdt/assets/679236/6b2a6c1a-32be-4ba3-8b1d-dc5868a29a97)

However forcing the application back in the command line `-application org.eclipse.cdt.debug.application.app` does get roughly the correct result:

This:

![image](https://github.com/eclipse-cdt/cdt/assets/679236/27c145db-77cb-4c25-b610-309cafda1201)


Followed by:

![image](https://github.com/eclipse-cdt/cdt/assets/679236/1e141006-9ae1-4126-915e-17f8bd6f6abc)

which has the mostly simplified menu. The startup time is longer as all features are enabled:

![image](https://github.com/eclipse-cdt/cdt/assets/679236/ed9f6e47-c022-45fd-b708-b167b775a388)

But that may be better than leaving things broken or removing the standalone debugger entirely.

**Comment by jonahgraham** [comment]
> TBH I was not aware of cdtdebug.sh at all, I did a regular maven build locally and then launched an eclipse application

That is good to know, thanks for confirming - the "manual" for the debugger is https://github.com/eclipse-cdt/cdt/blob/main/StandaloneDebugger.md which is linked from the release pages such as https://github.com/eclipse-cdt/cdt/releases/tag/CDT_11_5_0

> %cdt_sources_home%\debug\org.eclipse.cdt.debug.application.product\target\products\org.eclipse.cdt.debug.application.product\cdt-stand-alone-debugger-11.6.0-20240419-1619-win32.win32.x86_64.zip

That zip isn't published anywhere (it used to be a long time ago). That zip is basically how distros build the package they include.

> Are you sure that all these scripts are really required @jonahgraham ?

The scripts provide three benefits:

- User doesn't need to pass special command line arguments to normal eclipse.
- Help is produced instantly (`cdtdebug.sh --help`) and some command line checking is done
- And finally consistency with how it has been before, i.e cdtdebug.sh continues to be the entry point


Before the config.ini generation was removed in #761 the script also passed the command line arguments that meant the reduced config was used. As the command line is getting simplified now, users can certainly just run `eclipse -application org.eclipse.cdt.debug.application.app`

**Comment by ruspl-afed** [comment]
In this case please accept my apologies for breaking it. Perhaps we can restore it using something simple, like maven-exec

**Comment by jonahgraham** [comment]
No worries - the breakage was with no real effect since the generated `config.ini` often didn't work anyway. I'm preparing an alternative solution now.
