### ISSUE TITLE
Compiler path in compile_commands.json must be absolute

### ISSUE THREAD

**Issue by alicetrifu** [eclipse-cdt/cdt#822]
Currently, the path to the compiler in the compile_commands.json file is not absolute; it is just the name of the executable. For better functionality, it is necessary to specify the exact location of the compiler in the file.
eg:
![image](https://github.com/eclipse-cdt/cdt/assets/61590135/6fabd962-06f8-466d-90e9-609fecd8e43a)

**Comment by jonahgraham** [comment]
Thanks @alicetrifu for the fix.
