### ISSUE TITLE
JSON Compilation Database Generator properties page is visible in non C/C++ projects

### ISSUE THREAD

**Issue by ghentschke** [eclipse-cdt/cdt#847]
**Describe the bug**
The JSON Compilation Database Generator properties page is visible in non C/C++ projects as well:

**To Reproduce**
1. Create a non C/C++ project in Eclipse IDE with CDT
2. Open Properties of that project

**Expected behavior**
The JSON Compilation Database Generator properties page should not be visible/enabled in non C/C++ projects.

**Screenshots**
![image](https://github.com/eclipse-cdt/cdt/assets/123444711/77faf2cb-335c-468f-ad96-5f1001aacd9c)

**Version Information (please complete the following information):**
 - Windows 10/11
 - Eclipse 2024-06 (4.32)
 - CDT main branch on commit 3875408 Speed up closing all file descriptors in the child process (Fixes #835) from 2024-06-28

**Comment by jonahgraham** [comment]
I am targetting this for the 10.6 branch and I will cherry-pick it to that branch soon.

**Comment by ghentschke** [comment]
IMO this can be closed?

**Comment by jonahgraham** [comment]
> IMO this can be closed?

The 11.6.1 release will be out soon and includes this fix.
