### ISSUE TITLE
CMakeToolChainManager removeToolChainFile not working

### ISSUE THREAD

**Issue by alirana01** [eclipse-cdt/cdt#908]
**Describe the bug**
CMakeToolChainManager is not removing the cmake toolchains. I can still see them even after calling the remove function.

**To Reproduce**
We have cmake toolchains that are initialized like and added using the CMakeToolChainManager. The issue is that when I am trying to remove them by calling the removeToolChainFile the tcId calculated there is at times different than the one that is used while adding them. Because of this the toolchains are not removed and I am still able to see them in the Preferences.

**Expected behavior**
Calling the toolchain manager's remove method should remove the toolchains from the eclipse preferences.

**Code**
My function to remove all CMake ToolChains.
```
	/**
	 * Removes all the cmake toolchains in the current environment
	 */
	public void removeCmakeToolChains()
	{
		ICMakeToolChainManager cmakeTcManager = CCorePlugin.getService(ICMakeToolChainManager.class);
		List<ICMakeToolChainFile> cIcMakeToolChainFiles = new ArrayList<>(cmakeTcManager.getToolChainFiles());
		for (ICMakeToolChainFile cmakeToolchain : cIcMakeToolChainFiles)
		{
			try
			{
				cmakeTcManager.removeToolChainFile(cmakeToolchain);
			}
			catch (Exception e)
			{
				Logger.log(e);
			}
		}
	}
```
	

The addToolChainFile(ICMakeToolChainFile file) function in CMakeToolChainManager is calculating tcId using 
`makeToolChainId(toolchain);`

but the removeToolChainFile(ICMakeToolChainFile file) is using this
```
String tcId = makeToolChainId(file.getProperty(CMakeBuildConfiguration.TOOLCHAIN_TYPE),
				file.getProperty(CMakeBuildConfiguration.TOOLCHAIN_ID));
```

I am not sure why these two are different while debugging calculating the tcId using the way in add I am able to successfully remove these.

**Version Information (please complete the following information):**
 - OS and OS Version/extra details: [e.g. Windows, Linux, macOS] (all)
 - Eclipse Version: v4.33.0 2024-09
 - CDT Version: 11.6.1

**Comment by alirana01** [comment]
I also wanted to become a contributor to eclipse and have a branch and some code ready to push but seems like I need to have some access before doing that I have followed the CONTRIBUTING.MD guide and waiting for the approval to get it

**Comment by jonahgraham** [comment]
> I also wanted to become a contributor to eclipse and have a branch and some code ready to push but seems like I need to have some access before doing that I have followed the CONTRIBUTING.MD guide and waiting for the approval to get it

Contributions are certainly welcome. Please push your change to your fork and create a PR and thanks in advance!

See [Create a Pull Request for your commit(s).](https://github.com/eclipse-cdt/cdt/blob/main/CONTRIBUTING.md#:~:text=Create%20a%20Pull%20Request%20for%20your%20commit(s).) for instructions.
