### ISSUE TITLE
(Quick) Search in editor unfolds collpased regions with matches immediatly while typing

### ISSUE THREAD

**Issue by ronso0** [eclipse-cdt/cdt#910]
When typing in the new floating Search widget, previously ccollapsed region (methods) with matches are unfolded immediatley.
If there is, I did not find the options in **Window -> Preferences** to change that behavior. Ie. restore the behavior of the previous Search implementation (oldschool moveable dialog, my previous version was 2024-03).

**To Reproduce**
* open a cpp file in the editor
* collapse all regions (methods, comments etc.)
* bring up the Search widget with Ctrl+F
* type a string

**Expected behavior**
Edit position, scroll position and collapsed state remains untouched until I hit Enter to search

**Actual behaviour**
As soon as I type (or rather after the debounce timeout), the editor jumps to the next match, i.e. unfolds regions that I intended to skip (type, move cursor in editor, hit Enter to search downwards).

**Version Information (please complete the following information):**
Unbuntu Studio 20.04.5
Eclipse 2024-09 (4.33.0)
CDT 11.6.1.202406241230

**Comment by jonahgraham** [comment]
Have a look at https://eclipse.dev/eclipse/news/4.33/platform.php#find-replace-overlay there is a screenshot that shows where the preference is to change back to the old find dialog.

**Comment by ronso0** [comment]
Okay, thanks for the hint!

But, about the actual 'bug': is auto-search really a desired feature?
It's different to all search/replace dialogs I encountered where I have to press Enter to search.
The docu you linked says
> **By default**, it performs a "search as you type" ...

Can this be disabled with some config flag?

___
FWIW while I'm at it I'd like to share my impression with the new Search overlay.
(I'm aware this probably not the best place, but anyway..)

**Pros**
* it's compact
* pre-defined positions (top / bottom) are okay (well, I can't move it anyway :laughing: )

**Cons**
* Tab key navigation/usage
   * going from Find to Replace field takes 10! keypresses
   * using Ctrl+F / Ctrl+R to jump between the two would be cool, but doesn't work:
   Ctrl+F in Replace field closes the dialog
   Ctrl+R in Find field while Replace bar is visible closes Replace bar
   * Enter is context dependent (Find next / Replace current match), say I want to replace only a few matches the keyboard UX is sub optimal
* option icons  are hard to recognize with the dark theme, same for the keyboard focus frame
![image](https://github.com/user-attachments/assets/35f6c1c6-dd98-410e-99e8-0c06d14873ce)
