### ISSUE TITLE
Use org.eclipse.debug.ui.contextViewBindings for 'org.eclipse.cdt.visualizer.view' and 'org.eclipse.cdt.debug.ui.executablesView' views.

### ISSUE THREAD

**Issue by raghucssit** [eclipse-cdt/cdt#918]
The problem is when the eclipse switches to `Debug` perspective '`org.eclipse.cdt.visualizer.view`' and '`org.eclipse.cdt.debug.ui.executablesView`' views are populated by default. Irrespective of debug context.

If we debug java application these views are not needed. So we can bind them to `contextId="org.eclipse.cdt.debug.ui.debugging"`.

Already many views like `Memory View` and `Debug Console View` are using this approach.
We can use same approach to `Visualizer View` and `Executable View`.

It looks like below when i try to debug Java application there is no CPP project in the workspace.
![committer-2024-09-after-cdt](https://github.com/user-attachments/assets/417f001a-8f0a-42ba-9051-073c5dc47844)

**Comment by raghucssit** [comment]
![image](https://github.com/user-attachments/assets/00ab5ab8-4b6f-475f-8923-cda5cf288743)
The above Refresh Action is missing on CDT package release 2024-09.
Is this expected or a bug ?

**Comment by jonahgraham** [comment]
PS Please create new issues/discussions for new topics - see #920

**Comment by raghucssit** [comment]
> PS Please create new issues/discussions for new topics - see #920

Ok sure. Thanks.

**Comment by jonahgraham** [comment]
Completed in #919
