### ISSUE TITLE
Bundle org.eclipse.equinox.p2.repository is not started when using Maven

### ISSUE THREAD

**Issue by yaccwang** [eclipse-cdt/cdt#927]
Hello everyone,

I'm encountering an issue while trying to compile the CDT source code using Maven. The error message I receive is:
Bundle org.eclipse.equinox.p2.repository is not started

Here are some details about my setup:
1. CDT version: CDT_11_3_0 54a7f61
2. Maven version: 3.9.5
3. The compilation worked correctly last year, but now I am facing this error.
I would appreciate any guidance on how to resolve this issue. Thank you!

**Comment by jonahgraham** [comment]
@yaccwang This is a tycho issue - please see the discussion in https://github.com/eclipse-tycho/tycho/discussions/3738

You can try updating tycho version, but you may have to make other changes on the branch too to get a valid/current target platform. 

e.g. apply:

```diff
From f23d50e56f75ba2ab5c94de8995054e20fe27afe Mon Sep 17 00:00:00 2001
From: Jonah Graham <jonah@kichwacoders.com>
Date: Wed, 30 Oct 2024 11:32:42 -0400
Subject: [PATCH] Update tycho to newer version

---
 .mvn/extensions.xml | 2 +-
 pom.xml             | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/.mvn/extensions.xml b/.mvn/extensions.xml
index 879349e7b7..3c6953b6d8 100644
--- a/.mvn/extensions.xml
+++ b/.mvn/extensions.xml
@@ -3,6 +3,6 @@
   <extension>
     <groupId>org.eclipse.tycho</groupId>
     <artifactId>tycho-build</artifactId>
-    <version>4.0.1</version>
+    <version>4.0.7</version>
   </extension>
 </extensions>
diff --git a/pom.xml b/pom.xml
index 9207adb6eb..8b22cc3399 100644
--- a/pom.xml
+++ b/pom.xml
@@ -26,7 +26,7 @@
 
        <properties>
                <required-maven-version>3.9.1</required-maven-version>
-               <tycho-version>4.0.1</tycho-version>
+               <tycho-version>4.0.7</tycho-version>
                <cbi-plugins.version>1.3.4</cbi-plugins.version>
                <sonar.core.codeCoveragePlugin>jacoco</sonar.core.codeCoveragePlugin>
                <cdt-site>http://ci.eclipse.org/cdt/job/cdt-master/lastSuccessfulBuild/artifact/releng/org.eclipse.cdt.repo/target/repository</cdt-site>
-- 
2.41.0
```

and you may have to ensure that the versions of dependencies are correct for your use case, e.g:

https://github.com/eclipse-cdt/cdt/blob/1502092865a93e43d8e93ff1bf994b2f5d12d167/releng/org.eclipse.cdt.target/cdt.target#L22

Let me know if you run into any trouble rebuilding CDT 11.3. However officially we don't support any old versions, so you may run into blocking issues, so the project is unlikely to apply any changes for this.

**Comment by yaccwang** [comment]
Thank you very much!
I updated Tycho to 4.0.7, and the error disappeared. However, as you predicted, a new error appeared in cdt/releng/org.eclipse.cdt.target/cdt.target. Since I'm not familiar with Maven or Tycho, I couldn't resolve it. 
I had to give up on CDT 11.3 and switch to CDT 11.6.1, which has now compiled successfully.
 Nonetheless, I really appreciate your help!

**Comment by yaccwang** [comment]
> @yaccwang This is a tycho issue - please see the discussion in [eclipse-tycho/tycho#3738](https://github.com/eclipse-tycho/tycho/discussions/3738)
> 
> You can try updating tycho version, but you may have to make other changes on the branch too to get a valid/current target platform.
> 
> e.g. apply:
> 
> ```diff
> From f23d50e56f75ba2ab5c94de8995054e20fe27afe Mon Sep 17 00:00:00 2001
> From: Jonah Graham <jonah@kichwacoders.com>
> Date: Wed, 30 Oct 2024 11:32:42 -0400
> Subject: [PATCH] Update tycho to newer version
> 
> ---
>  .mvn/extensions.xml | 2 +-
>  pom.xml             | 2 +-
>  2 files changed, 2 insertions(+), 2 deletions(-)
> 
> diff --git a/.mvn/extensions.xml b/.mvn/extensions.xml
> index 879349e7b7..3c6953b6d8 100644
> --- a/.mvn/extensions.xml
> +++ b/.mvn/extensions.xml
> @@ -3,6 +3,6 @@
>    <extension>
>      <groupId>org.eclipse.tycho</groupId>
>      <artifactId>tycho-build</artifactId>
> -    <version>4.0.1</version>
> +    <version>4.0.7</version>
>    </extension>
>  </extensions>
> diff --git a/pom.xml b/pom.xml
> index 9207adb6eb..8b22cc3399 100644
> --- a/pom.xml
> +++ b/pom.xml
> @@ -26,7 +26,7 @@
>  
>         <properties>
>                 <required-maven-version>3.9.1</required-maven-version>
> -               <tycho-version>4.0.1</tycho-version>
> +               <tycho-version>4.0.7</tycho-version>
>                 <cbi-plugins.version>1.3.4</cbi-plugins.version>
>                 <sonar.core.codeCoveragePlugin>jacoco</sonar.core.codeCoveragePlugin>
>                 <cdt-site>http://ci.eclipse.org/cdt/job/cdt-master/lastSuccessfulBuild/artifact/releng/org.eclipse.cdt.repo/target/repository</cdt-site>
> -- 
> 2.41.0
> ```
> 
> and you may have to ensure that the versions of dependencies are correct for your use case, e.g:
> 
> https://github.com/eclipse-cdt/cdt/blob/1502092865a93e43d8e93ff1bf994b2f5d12d167/releng/org.eclipse.cdt.target/cdt.target#L22
> 
> Let me know if you run into any trouble rebuilding CDT 11.3. However officially we don't support any old versions, so you may run into blocking issues, so the project is unlikely to apply any changes for this.

Thank you very much!
I updated Tycho to 4.0.7, and the error disappeared. However, as you predicted, a new error appeared in cdt/releng/org.eclipse.cdt.target/cdt.target. Since I'm not familiar with Maven or Tycho, I couldn't resolve it.
I had to give up on CDT 11.3 and switch to CDT 11.6.1, which has now compiled successfully.
Nonetheless, I really appreciate your help!
