### ISSUE TITLE
C++ dialect

### ISSUE THREAD

**Issue by gpeterhoff** [eclipse-cdt/cdt#944]
In the setting C/C++Buid -> Settings there is no support for
- C++20, but only for the predecessor C++2a
- C++23
- C++26

**Comment by marcelr** [comment]
I have solved it by unselecting the "Language standard" and writing manually 
```
-std=c++23
```

![grafik](https://github.com/user-attachments/assets/c4a94dbf-27fc-4aee-b767-0031c8351f39)

**Comment by gpeterhoff** [comment]
Thank you for your answer. But that's not what I meant. I just want the current C++ standards to be available in the selection list and not always lag years behind the developments.
- C++20 is not available, only C++2a
- C++23 is not available
- C++26 is not available

It would also make sense to provide additional presets for known compilers. For example -std=gnu++X unlocks u/int128 and libquadmath.

cu
Gero

Translated with DeepL.com (free version)
