### ISSUE TITLE
missing Windows on Arm64 natives in CDT

### ISSUE THREAD

**Issue by chirontt** [eclipse-cdt/cdt#969]
**Description**

Eclipse IDE for C/C++ Developers, version [2024-12](https://www.eclipse.org/downloads/packages/release/2024-12/r/eclipse-ide-cc-developers), is now available for Windows on Arm64 (WoA):

![image](https://github.com/user-attachments/assets/783259e2-de6a-4403-9731-47e081d4e52d)

But running it on a WoA box shows some deficiencies:
- Opening a `Terminal` view and choosing the `Local Terminal` seems OK (i.e. the `CMD` window is showing properly in a view), but any command entered to that view would show nothing, due to exceptions thrown in the Eclipse console:
```
!ENTRY org.eclipse.cdt.core.native 4 0 2024-12-12 19:47:13.627
!MESSAGE Failed to load the PTY library. This may indicate a configuration problem, but can be ignored if no further problems are observed.
!STACK 0
java.lang.UnsatisfiedLinkError: no winpty in java.library.path: C:\apps\eclipse\cpp-2024-12;C:\WINDOWS\Sun\Java\bin;...
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base/java.lang.System.loadLibrary(System.java:2063)
        at org.eclipse.cdt.utils.pty.PTY.<clinit>(PTY.java:307)
        at org.eclipse.tm.terminal.connector.local.launcher.LocalLauncherDelegate.createTerminalConnector(LocalLauncherDelegate.java:317)
        at org.eclipse.tm.terminal.view.ui.services.TerminalService.createTerminalConnector(TerminalService.java:246)
        at org.eclipse.tm.terminal.view.ui.services.TerminalService.executeServiceOperation(TerminalService.java:168)
        at org.eclipse.tm.terminal.view.ui.services.TerminalService.openConsole(TerminalService.java:258)
        at org.eclipse.tm.terminal.connector.local.launcher.LocalLauncherDelegate.execute(LocalLauncherDelegate.java:224)
        at org.eclipse.tm.terminal.view.ui.internal.handler.LaunchTerminalCommandHandler.execute(LaunchTerminalCommandHandler.java:85)
```
- Building a simple project seems (surprisingly) working; here's its console output:

![image](https://github.com/user-attachments/assets/a15b392e-66c4-499a-b306-fdadb7b7f43a)

but the Eclipse console shows some exceptions:
```
!ENTRY org.eclipse.cdt.core.native 4 0 2024-12-12 20:14:58.627
!MESSAGE no spawner in java.library.path: C:\apps\eclipse\cpp-2024-12;C:\WINDOWS\Sun\Java\bin;...
```

From the above exceptions, I guess those `winpty` and `spawner` binaries (for WoA) are not available in the Eclipse IDE package, causing e.g. the `Terminal` not working.

**Version Information**
 - OS and OS Version/extra details: Windows 11 on Arm64
 - Eclipse Version: 2024-12 (4.34)
 - CDT Version from Help -> About -> Installation Details -> Features tab: 11.6.1

**Additional context**
Browsing the CDT source code, I notice that there is no WoA native fragment equivalent to the existing one for `x84_64` ([org.eclipse.cdt.core.win32.x86_64/os/win32/x86_64](https://github.com/eclipse-cdt/cdt/tree/main/core/org.eclipse.cdt.core.win32.x86_64/os/win32/x86_64)) so I guess those `pty.dll`, `spawner.dll`, `starter.exe`, `winpty.dll`, `winpty-agent.exe` binaries need be recompiled for WoA, for a new `org.eclipse.cdt.core.win32.aarch64` fragment.

I will submit a PR for this new fragment for WoA. But the sticky point is: how will the CDT team re-compile those binaries for WoA? (I can't submit the WoA binaries built by me, for obvious security reason.) Does the team have access to a WoA box to build them?

**Comment by jonahgraham** [comment]
Thanks @chirontt - that would be great.

We use Docker and cross-compile Windows for x86-64 at the moment. See for example [here](https://github.com/eclipse-cdt/cdt/blob/de78b0f4a26d641c74bef88f235a063496b1e19a/docker/cdt-infra-eclipse-full/ubuntu-18.04/Dockerfile#L19) where we install gcc-mingw-w64-x86-64 and the [building documentation for natives](https://github.com/eclipse-cdt/cdt/blob/main/BUILDING.md#native)

How it works is that as part of a PR you provide the DLLs as built with the docker images and explained in the above documentation. Our build verifies, by rebuilding, that the DLLs in your commit match the sources with [this script](https://github.com/eclipse-cdt/cdt/blob/06c8b01d836bf9a02e61f1375217a46729c53e71/releng/scripts/do_rebuild_natives.sh) as part of the [this GHA workflow](https://github.com/eclipse-cdt/cdt/blob/c9fa638d3d397ef26b80a92170bfd7e4b6141574/.github/workflows/code-cleanliness.yml)

There are some challenges we need to overcome to update this workflow for WoA, mostly that we are based on Ubuntu 18.04 LTS at the moment, which I assume doesn't have WoA cross compilers. The timing is good as CDT 12.0 is the next release, so updating this build infrastructure to a new version of Ubuntu is well timed.

If you can contribute the sources and identify if such a cross-compiler exists in the Ubuntu ecosystem, I can handle the infra changes. If you want to even make the Dockerfile changes, it would be welcome too.

Please let me know how else I can support you on this task.

**Comment by jonahgraham** [comment]
> Does the team have access to a WoA box to build them?

To be explicit, at the moment we do not within the project. The Eclipse Foundation does, and if there is no cross-compile option in the same way we are doing it now, we can look at some manual builds on that infrastructure (and automate it if it becomes useful)

**Comment by chirontt** [comment]
> We use Docker and cross-compile Windows for x86-64

This wouldn't work for WoA, as the current/latest GCC 14 compiler itself doesn't support output of WoA binaries; it will be [supported in GCC 15](https://www.phoronix.com/news/GCC-aarch64-w64-mingw32) though in next year's release.

In the meantime we have to use a different compiler in WoA, and in my PR #971 I describe in details the MSYS2/CLANGARM64 shell which provides a unixy environment, plus a LLVM-based MinGW compiler package, to successfully re-compile the CDT binaries in WoA.

Alternatively, to do cross-compiling from a Windows x64 host, this [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) compiler may work. And it also provides a Ubuntu tarball, so it **might** be able to cross-compile to WoA from Linux! I need more research on this compiler.

**Comment by jonahgraham** [comment]
Does GitHub have any runners that would be suitable? e.g. can we have a GitHub action that builds these files?

**Comment by jonahgraham** [comment]
Based on (from https://github.com/eclipse-cdt/cdt/pull/971#issuecomment-2544570683)

> and there won't be any need for a WoA box to do tons of manual stuff mentioned in the description above.

it sounds like it isn't relevant anyways. If it does become relevant, we have access to some non-free resources within the project.

**Comment by chirontt** [comment]
@jonahgraham I'm checking out the CDT's `support_windows_on_arm64` branch, building it with `mvn clean verify -DskipTests=true` and the build is fine. Will test the build with `x64` platform first, then with the WoA platform.

But I've seen some disturbing behaviours of `winpty` in the `x64` platform, for the **current** Eclipse IDE. Here are the steps to see them:
- take the current Eclipse IDE for C/C++ Developers (version [2024-12](https://www.eclipse.org/downloads/packages/release/2024-12/r/eclipse-ide-cc-developers)) which contains the CDT version 11.6.1
- modify its `ecipse.ini` file by adding the following property:
```
-Dorg.eclipse.cdt.core.conpty_enabled=true
```
- start up the Eclipse IDE, show the `Terminal` view and open the `Local Terminal` in it. Type some command in the local terminal, say `dir`, to see that everything is working fine with it. Then close the local terminal and its `Terminal` view
- shut down the IDE, then change its `eclipse.ini` file with:
```
-Dorg.eclipse.cdt.core.conpty_enabled=false
```
i.e. force the disabling of `ConPTY`
- now start up the Eclipse IDE again, show the `Terminal` view and open the `Local Terminal` again, what will you see on your `x64` machine?
- on my `x64` machine, I get an **external** Windows Terminal opened at the same time with the local terminal view in Eclipse, i.e.
 
![image](https://github.com/user-attachments/assets/7ca9694c-6938-45ba-a197-a06783f1e2c3)

and the two terminals share the same I/O for all commands executed in either of them!

![image](https://github.com/user-attachments/assets/32382d1a-30df-41ec-947b-fa5d8118c1da)

Can you reproduce the problem with your Windows `x64` box? I hope it's not unique to my Windows 11 (x64) box!

**Comment by jonahgraham** [comment]
> Can you reproduce the problem with your Windows x64 box? I hope it's not unique to my Windows 11 (x64) box!

Yes. The version on winpty is ancient in CDT and when I last tested it it worked fine on a Windows 7 box. The issue is that Windows Console team have been very active in the last few years and it seems the way we (winpty really) is launching the hidden console is not working anymore.

If I was a little braver I would rip out winpty implementation entirely. `-Dorg.eclipse.cdt.core.conpty_enabled=false` really only existed to ensure that when I first wrote and enabled conpty if I had regressed any user flows we could back out of it. I don't intend to support `-Dorg.eclipse.cdt.core.conpty_enabled=false`.

**Comment by jonahgraham** [comment]
> @jonahgraham I'm checking out the CDT's `support_windows_on_arm64` branch, building it with `mvn clean verify -DskipTests=true` and the build is fine. Will test the build with `x64` platform first, then with the WoA platform.

That is fine that you are doing it locally - I am working on ensuring a fully signed/etc version works too. The build [is running now](https://ci.eclipse.org/cdt/job/cdt/job/support_windows_on_arm64/11/) after a few false starts and hopefully this one will run to conclusion and there aren't any other small updates that I need to do.

I will let you know when it is ready, but you can have a look on https://download.eclipse.org/tools/cdt/builds/cdt/ - there shoudl be a new `support_windows_on_arm64` directory when the build succeeds which will have the p2 site you can install from into your 2024-12 SDK.

**Comment by jonahgraham** [comment]
> The version on winpty is ancient in CDT and when I last tested it it worked fine on a Windows 7 box. 

I spun it up on a Windows 11 box and if you use conhost instead of Windows Terminal the window is correctly hidden. WinPTY is only realistically useful if you also use conhost, so that makes sense.

This is the Windows setting you have to change to reproduce this:

![image](https://github.com/user-attachments/assets/ca467ffa-5caf-4b7f-b2df-e386df1df1f0)

(And with that I hope that is the last time I have to deal with WinPTY until we decide to delete it from the sources!)

**Comment by jonahgraham** [comment]
The [build](https://www.reddit.com/r/csharp/comments/19dr2ry/how_can_i_tell_vs_2022_to_use_the_old_console/) was successful. @chirontt can you please try out this p2 site and let me know if it seems ok https://download.eclipse.org/tools/cdt/builds/cdt/support_windows_on_arm64/

**Comment by chirontt** [comment]
Yes, that p2 site works fine. I use a fresh Eclipse SDK 4.34 package for WoA, and update it with that p2 site to install the needed CDT features/plugins. The `Terminal` view testing is good without any issues. With the `winpty/pty` libraries (for WoA) removed from the CDT distribution, the `ConPTY` class works fine in WoA.

**Comment by jonahgraham** [comment]
Thanks @chirontt for the contribution and testing the result. I have now merged the fix into main
